-- Additional translations for remaining Chinese text in atomCommon
USE rpa;

-- Excel atoms that still have Chinese
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"添加Excel工作表"', '"title":"Add Excel Sheet"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取已打开的Excel对象"', '"title":"Get Opened Excel Object"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"创建Excel"', '"title":"Create Excel"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"写入Excel"', '"title":"Write Excel"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"读取Excel内容"', '"title":"Read Excel Content"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"设置单元格格式"', '"title":"Set Cell Format"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"复制Excel单元格"', '"title":"Copy Excel Cell"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"粘贴Excel单元格"', '"title":"Paste Excel Cell"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"删除Excel单元格"', '"title":"Delete Excel Cell"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取Excel工作表名称"', '"title":"Get Excel Sheet Names"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"清除Excel区域内容"', '"title":"Clear Excel Range"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"插入Excel行或列"', '"title":"Insert Excel Row/Column"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取Excel行数"', '"title":"Get Excel Row Count"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取Excel列数"', '"title":"Get Excel Column Count"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取Excel第一个可用行"', '"title":"Get Excel First Available Row"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取Excel第一个可用列"', '"title":"Get Excel First Available Column"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"设置Excel行高"', '"title":"Set Excel Row Height"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"设置Excel列宽"', '"title":"Set Excel Column Width"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取Excel单元格颜色"', '"title":"Get Excel Cell Color"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"合并或拆分Excel单元格"', '"title":"Merge/Split Excel Cell"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"移动Excel工作表"', '"title":"Move Excel Sheet"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"删除Excel工作表"', '"title":"Delete Excel Sheet"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"重命名Excel工作表"', '"title":"Rename Excel Sheet"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"复制Excel工作表"', '"title":"Copy Excel Sheet"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"查找或替换Excel内容"', '"title":"Find/Replace Excel Content"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"插入Excel图片"', '"title":"Insert Excel Image"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"插入Excel公式"', '"title":"Insert Excel Formula"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"创建Excel批注"', '"title":"Create Excel Comment"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"删除Excel批注"', '"title":"Delete Excel Comment"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"Excel区域文本转数字"', '"title":"Excel Range Text to Number"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"Excel区域数字转文本"', '"title":"Excel Range Number to Text"') WHERE atom_key = 'atomCommon';

-- Keyboard atoms
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"键盘输入"', '"title":"Keyboard Input"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"鼠标点击"', '"title":"Mouse Click"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"键盘模拟按键"', '"title":"Keyboard Simulate Key"') WHERE atom_key = 'atomCommon';

-- Data processing atoms
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"数学操作"', '"title":"Math Operations"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"生成随机数"', '"title":"Generate Random Number"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"四舍五入"', '"title":"Round Number"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"自增自减"', '"title":"Increment/Decrement"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取绝对值"', '"title":"Get Absolute Value"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"数学计算"', '"title":"Math Calculation"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"字符串操作"', '"title":"String Operations"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"文本提取内容"', '"title":"Extract Text Content"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"文本替换内容"', '"title":"Replace Text Content"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"列表聚合为文本"', '"title":"List to Text"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"文本分割为列表"', '"title":"Text Split to List"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"文本合并"', '"title":"Text Merge"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"文本补齐至固定长度"', '"title":"Pad Text to Length"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"文本去除两侧空格"', '"title":"Trim Text Spaces"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"截取固定长度文本"', '"title":"Substring Fixed Length"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"更改文本大小写"', '"title":"Change Text Case"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取文本长度"', '"title":"Get Text Length"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"JSON字符串互转"', '"title":"JSON String Convert"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"其他格式转文本"', '"title":"Format to Text"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"文本转其他格式"', '"title":"Text to Format"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"列表操作"', '"title":"List Operations"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"创建新列表"', '"title":"Create New List"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"清空列表"', '"title":"Clear List"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"列表插入值"', '"title":"List Insert Value"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"列表修改值"', '"title":"List Modify Value"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取值在列表位置"', '"title":"Get Value Position in List"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"列表删除值"', '"title":"List Remove Value"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"列表随机打乱顺序"', '"title":"List Random Shuffle"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"剔除列表中的多项"', '"title":"Remove Multiple from List"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"列表反转"', '"title":"Reverse List"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"列表合并"', '"title":"Merge Lists"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取两个列表的重复项"', '"title":"Get List Duplicates"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"根据索引获取列表值"', '"title":"Get List Value by Index"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"字典操作"', '"title":"Dictionary Operations"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"创建新字典"', '"title":"Create New Dictionary"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"字典设置值"', '"title":"Dictionary Set Value"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"字典删除值"', '"title":"Dictionary Delete Value"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"字典获取值"', '"title":"Dictionary Get Value"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取字典所有值"', '"title":"Get All Dictionary Values"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"时间操作"', '"title":"Time Operations"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"设置时间"', '"title":"Set Time"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"时间对象转时间戳"', '"title":"DateTime to Timestamp"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"时间戳转时间对象"', '"title":"Timestamp to DateTime"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取时间差"', '"title":"Get Time Difference"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"输出指定格式时间文本"', '"title":"Output Formatted Time Text"') WHERE atom_key = 'atomCommon';

-- OS operations
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"操作系统"', '"title":"Operating System"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"写入文件"', '"title":"Write File"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"读取文件"', '"title":"Read File"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"查找文件"', '"title":"Find File"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"等待文件"', '"title":"Wait for File"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取文件编码类型"', '"title":"Get File Encoding"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取文件信息"', '"title":"Get File Info"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取文件列表"', '"title":"Get File List"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"上传文件至共享文件夹"', '"title":"Upload to Shared Folder"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"从共享文件夹下载文件"', '"title":"Download from Shared Folder"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"文件夹操作"', '"title":"Folder Operations"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"打开文件夹"', '"title":"Open Folder"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"清空文件夹"', '"title":"Clear Folder"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取文件夹列表"', '"title":"Get Folder List"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"压缩/解压"', '"title":"Compress/Decompress"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"压缩"', '"title":"Compress"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"解压"', '"title":"Decompress"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"系统命令"', '"title":"System Commands"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"运行或打开"', '"title":"Run or Open"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取进程PID"', '"title":"Get Process PID"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"终止进程"', '"title":"Terminate Process"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"截图"', '"title":"Screenshot"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"屏幕截图"', '"title":"Screen Screenshot"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"剪切板"', '"title":"Clipboard"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"复制到剪切板"', '"title":"Copy to Clipboard"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"清空剪切板"', '"title":"Clear Clipboard"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取剪切板"', '"title":"Get Clipboard"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"加解密/编解码"', '"title":"Encrypt/Decrypt"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"SHA加密"', '"title":"SHA Encrypt"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"MD5加密"', '"title":"MD5 Encrypt"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"对称解密"', '"title":"Symmetric Decrypt"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"对称加密"', '"title":"Symmetric Encrypt"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"Base64解码"', '"title":"Base64 Decode"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"Base64编码"', '"title":"Base64 Encode"') WHERE atom_key = 'atomCommon';

-- Network operations
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"HTTP下载"', '"title":"HTTP Download"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"创建FTP连接"', '"title":"Create FTP Connection"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"关闭FTP连接"', '"title":"Close FTP Connection"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取工作目录(FTP)"', '"title":"Get Working Directory (FTP)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"切换工作目录(FTP)"', '"title":"Change Working Directory (FTP)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"创建文件夹(FTP)"', '"title":"Create Folder (FTP)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取文件/文件夹(FTP)"', '"title":"Get Files/Folders (FTP)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"上传文件/文件夹(FTP)"', '"title":"Upload File/Folder (FTP)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"重命名文件/文件夹(FTP)"', '"title":"Rename File/Folder (FTP)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"下载文件/文件夹(FTP)"', '"title":"Download File/Folder (FTP)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"删除文件/文件夹(FTP)"', '"title":"Delete File/Folder (FTP)"') WHERE atom_key = 'atomCommon';

-- CV and dialog
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"CV图像"', '"title":"CV Image"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"点击图像"', '"title":"Click Image"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"鼠标悬浮在图像上"', '"title":"Mouse Hover on Image"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"等待图像"', '"title":"Wait for Image"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"图像输入框输入"', '"title":"Image Input Box"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"消息提示框"', '"title":"Message Dialog"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"输入对话框"', '"title":"Input Dialog"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"选择对话框"', '"title":"Selection Dialog"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"日期时间选择框"', '"title":"DateTime Picker"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"文件选择对话框"', '"title":"File Selection Dialog"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"自定义对话框"', '"title":"Custom Dialog"') WHERE atom_key = 'atomCommon';

-- Script and enterprise
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"自定义脚本"', '"title":"Custom Script"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"JS脚本"', '"title":"JS Script"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"卓越中心"', '"title":"Excellence Center"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取共享变量"', '"title":"Get Shared Variable"') WHERE atom_key = 'atomCommon';

-- Feishu (keep as is or translate)
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"飞书"', '"title":"Feishu"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"连接到多维表格"', '"title":"Connect to Multi-sheet"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"列出记录（筛选）"', '"title":"List Records (Filtered)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"列出记录（指定）"', '"title":"List Records (Specified)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"创建记录"', '"title":"Create Record"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"更新记录"', '"title":"Update Record"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"删除记录"', '"title":"Delete Record"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"列出数据表"', '"title":"List Tables"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"新增数据表"', '"title":"Add Table"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"删除数据表"', '"title":"Delete Table"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"重命名数据表"', '"title":"Rename Table"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"列出字段"', '"title":"List Fields"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"新增字段"', '"title":"Add Field"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"更新字段"', '"title":"Update Field"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"删除字段"', '"title":"Delete Field"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"连接数据表"', '"title":"Connect Table"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取工作表信息"', '"title":"Get Worksheet Info"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"设置筛选器"', '"title":"Set Filter"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"获取筛选结果"', '"title":"Get Filter Result"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"读取工作表数据"', '"title":"Read Worksheet Data"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"写入数据"', '"title":"Write Data"') WHERE atom_key = 'atomCommon';

-- commonAdvancedParameter section
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"打印输出变量值"', '"title":"Print Output Variable Value"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"label":"是"', '"label":"Yes"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"label":"否"', '"label":"No"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"执行前延迟(秒)"', '"title":"Delay Before Execution (seconds)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"执行后延迟(秒)"', '"title":"Delay After Execution (seconds)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"执行异常时"', '"title":"On Execution Error"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"label":"退出"', '"label":"Exit"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"label":"跳过"', '"label":"Skip"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"label":"重试"', '"label":"Retry"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"重试次数(次)"', '"title":"Retry Count (times)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"title":"重试间隔(秒)"', '"title":"Retry Interval (seconds)"') WHERE atom_key = 'atomCommon';

-- Types section
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"任意值"', '"desc":"Any value"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"template":"任何值"', '"template":"Any value"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"数值"', '"desc":"Number"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"转文本"', '"funcDesc":"To Text"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"resDesc":"字符串"', '"resDesc":"String"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"取整数部分"', '"funcDesc":"Get Integer Part"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"resDesc":"整数"', '"resDesc":"Integer"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"整数"', '"desc":"Integer"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"布尔值"', '"desc":"Boolean"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"template":"true或者false"', '"template":"true or false"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"字符串"', '"desc":"String"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"template":""你好""', '"template":""Hello""') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"删除两端空格"', '"funcDesc":"Remove Whitespace"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"转整数"', '"funcDesc":"To Integer"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"转数值"', '"funcDesc":"To Number"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"列表"', '"desc":"List"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"列表第@{p1:int}项"', '"funcDesc":"List item @{p1:int}"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"resDesc":"任意值"', '"resDesc":"Any value"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"列表倒数第@{p1:int}项"', '"funcDesc":"List item from end @{p1:int}"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"列表长度"', '"funcDesc":"List length"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"列表第@{p1:int}项到第@{p2:int}项"', '"funcDesc":"List items @{p1:int} to @{p2:int}"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"字典"', '"desc":"Dictionary"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"template":"{\"name\":\"小明\"}"', '"template":"{\"name\":\"John\"}"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"字典键@{p1:str}的值"', '"funcDesc":"Dictionary key @{p1:str} value"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"字典包含元素个数"', '"funcDesc":"Dictionary element count"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"文件路径"', '"desc":"File Path"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"根目录"', '"funcDesc":"Root Directory"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"父目录"', '"funcDesc":"Parent Directory"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"文件名称"', '"funcDesc":"File Name"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"文件名称(不带扩展名)"', '"funcDesc":"File Name (without extension)"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"文件扩展名"', '"funcDesc":"File Extension"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"文件夹路径"', '"desc":"Folder Path"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"日期时间"', '"desc":"DateTime"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"获取年份"', '"funcDesc":"Get Year"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"获取月份"', '"funcDesc":"Get Month"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"获取日"', '"funcDesc":"Get Day"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"获取小时"', '"funcDesc":"Get Hour"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"获取分钟"', '"funcDesc":"Get Minute"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"获取秒"', '"funcDesc":"Get Second"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"获取周几"', '"funcDesc":"Get Weekday"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"获取周数"', '"funcDesc":"Get Week Number"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"地址"', '"desc":"URL"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"元素"', '"desc":"Element"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"template":"JSON字符串"', '"template":"JSON string"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"网页元素"', '"desc":"Web Element"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"桌面元素"', '"desc":"Desktop Element"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"图像元素"', '"desc":"Image Element"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"密码"', '"desc":"Password"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"飞书对象"', '"desc":"Feishu Object"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"template":"飞书对象."', '"template":"Feishu Object."') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"对话框输出结果"', '"desc":"Dialog Output Result"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"浏览器对象"', '"desc":"Browser Object"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"template":"Browser对象"', '"template":"Browser Object"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"该网页的地址"', '"funcDesc":"Webpage URL"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"该网页的标题"', '"funcDesc":"Webpage Title"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"Word对象"', '"desc":"Word Object"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"template":"DocumentObject对象"', '"template":"DocumentObject Object"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"desc":"Excel对象"', '"desc":"Excel Object"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"template":"ExcelObj对象"', '"template":"ExcelObj Object"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"文件所在位置"', '"funcDesc":"File Location"') WHERE atom_key = 'atomCommon';
UPDATE c_atom_meta SET atom_content = REPLACE(atom_content, '"funcDesc":"第一个可用行"', '"funcDesc":"First Available Row"') WHERE atom_key = 'atomCommon';

SELECT 'Additional translations completed' as status;
