"""
Translate remaining RPA component config.yaml files from Chinese to English.
"""

import yaml
import re
from pathlib import Path

# Comprehensive translation dictionary
TRANSLATIONS = {
    # AI related
    "单轮会话": "Single-Turn Chat",
    "多轮会话": "Multi-Turn Chat",
    "知识问答": "Knowledge Q&A",
    "主题扩写": "Theme Expansion",
    "段落扩写": "Paragraph Expansion",
    "段落缩写": "Paragraph Abbreviation",
    "调用Dify流程": "Call Dify Workflow",
    "调用星辰Agent流程": "Call XC Agent Workflow",
    "合同要素提取": "Contract Element Extraction",
    "职位关键词生成": "Job Keyword Generation",
    "简历评分": "Resume Scoring",
    "大模型": "Model",
    "模型": "Model",
    "用户输入": "User Input",
    "模型选择": "Model Selection",
    "答案输出": "Answer Output",
    "保存会话": "Save Conversation",
    "窗口标题": "Window Title",
    "最大问答次数": "Maximum Q&A Rounds",
    "对话聊天记录输出": "Chat History Output",
    "文件路径": "File Path",
    "主题": "Theme",
    "段落": "Paragraph",
    "主题扩展结果输出": "Theme Expansion Result Output",
    "段落扩展结果输出": "Paragraph Expansion Result Output",
    "段落缩写结果输出": "Paragraph Abbreviation Result Output",
    "用户名": "Username",
    "流程密钥": "Workflow Secret",
    "是否上传文件": "Upload File",
    "变量名": "Variable Name",
    "变量值": "Variable Value",
    "文件类型": "File Type",
    "流程结果输出": "Workflow Result Output",
    "流程id": "Workflow ID",
    "工作流默认输入": "Workflow Default Input",
    "返回值": "Return Value",
    "合同输入方式": "Contract Input Method",
    "合同路径": "Contract Path",
    "合同文本内容": "Contract Text Content",
    "要素": "Elements",
    "效果验证": "Effect Validation",
    "返回要素结果": "Return Element Result",
    "职位名称": "Job Title",
    "职位描述": "Job Description",
    "招聘网站": "Recruitment Website",
    "职位关键词": "Job Keywords",
    "简历输入方式": "Resume Input Method",
    "简历文件路径": "Resume File Path",
    "简历文本内容": "Resume Text Content",
    "岗位评分体系": "Job Rating System",
    "岗位评分画像": "Job Rating Dimensions",
    "简历匹配结果": "Resume Match Result",
    "提示词": "Prompt",
    "问题": "Question",
    "角色": "Role",
    "进行回答": "will respond",
    "生成互动答案": "generate an interactive answer",
    "扮演角色": "play a role",
    "进行互动": "engage in interactions",
    "阅读": "read",
    "文档": "document",
    "回答": "answer",
    "扩写": "expand",
    "缩写": "abbreviate",
    "完成": "complete",
    "任务": "task",
    "提取": "extract",
    "根据": "based on",
    "生成": "generate",
    "关键词": "keywords",
    "评分": "score",
    "匹配": "match",
    
    # Email related
    "发送邮件": "Send Email",
    "接收邮件": "Receive Email",
    "收件人": "Recipient",
    "收件人邮箱": "Recipient Email",
    "抄送邮箱": "CC Email",
    "主题": "Subject",
    "是否为HTML格式": "Is HTML Format",
    "内容": "Content",
    "附件路径": "Attachment Path",
    "附件": "Attachment",
    "邮件服务器": "Mail Server",
    "其他邮件服务器": "Other Mail Server",
    "邮件服务器端口": "Mail Server Port",
    "是否使用SSL加密": "Use SSL Encryption",
    "发件人邮箱": "Sender Email",
    "发件人名称": "Sender Name",
    "密码/授权码": "Password/Authorization Code",
    "密送邮箱": "BCC Email",
    "智能填充表": "Smart Fill Table",
    "邮件服务器地址": "Mail Server Address",
    "IMAP服务器地址": "IMAP Server Address",
    "IMAP服务器端口": "IMAP Server Port",
    "用户邮件账号": "User Email Account",
    "授权码": "Authorization Code",
    "邮件最大返回数量": "Maximum Email Count",
    "仅未读邮件": "Unread Only",
    "保存附件": "Save Attachments",
    "保存目录": "Save Directory",
    "文件夹名称": "Folder Name",
    "标记为已读": "Mark as Read",
    "发件人中包含的内容": "Sender Contains",
    "收件人中包含的内容": "Recipient Contains",
    "主题中包含的内容": "Subject Contains",
    "正文中包含的内容": "Body Contains",
    "保存邮件列表": "Save Email List",
    "邮件": "Email",
    "邮箱": "Mailbox",
    "指定邮箱": "specified mailbox",
    "发送": "send",
    "接收": "receive",
    "邮件信息": "email information",
    "选择": "select",
    "输入": "enter",
    "返回": "return",
    "通过": "via",
    "包含": "contains",
    "关键字": "keywords",
    "过滤": "filter",
    "下载": "download",
    "获取": "obtain",
    "将": "will",
    
    # Dataprocess related
    "设置变量值": "Set Variable Value",
    "变量类型": "Variable Type",
    "设置后的变量值": "Variable Value After Setting",
    "JSON字符串互转": "JSON String Conversion",
    "其他格式转文本": "Other Format to Text",
    "文本转其他格式": "Text to Other Format",
    "转换类型": "Conversion Type",
    "转换结果": "Conversion Result",
    "创建新字典": "Create New Dictionary",
    "字典设置值": "Dictionary Set Value",
    "字典删除值": "Dictionary Delete Value",
    "字典获取值": "Dictionary Get Value",
    "获取字典所有键": "Get All Dictionary Keys",
    "获取字典所有值": "Get All Dictionary Values",
    "字典数据": "Dictionary Data",
    "键（key）": "Key",
    "值（value）": "Value",
    "新创建的字典": "Newly Created Dictionary",
    "设置后的字典": "Dictionary After Setting",
    "删除后的字典": "Dictionary After Deletion",
    "插入后的字典": "Dictionary After Insertion",
    "字典值": "Dictionary Value",
    "键列表": "Key List",
    "值列表": "Value List",
    "键不存在时处理方式": "Handling When Key Not Exists",
    "默认值": "Default Value",
    "创建新列表": "Create New List",
    "清空列表": "Clear List",
    "列表插入值": "List Insert Value",
    "列表修改值": "List Modify Value",
    "获取值在列表位置": "Get Value Position in List",
    "列表删除值": "List Remove Value",
    "列表排序": "List Sort",
    "列表随机打乱顺序": "List Random Shuffle",
    "剔除列表中的多项": "Remove Multiple Items from List",
    "列表反转": "List Reverse",
    "列表合并": "List Merge",
    "列表去重": "List Remove Duplicates",
    "获取两个列表的重复项": "Get Duplicate Items from Two Lists",
    "根据索引获取列表值": "Get List Value by Index",
    "获取列表长度": "Get List Length",
    "列表数据": "List Data",
    "列表类型": "List Type",
    "列表长度": "List Length",
    "初始值": "Initial Value",
    "创建的列表": "Created List",
    "清空后的列表": "Cleared List",
    "插入值": "Insert Value",
    "插入方式": "Insert Method",
    "插入位置": "Insert Position",
    "插入后的列表": "Inserted List",
    "位置索引": "Position Index",
    "新值": "New Value",
    "修改后的列表": "Modified List",
    "删除方式": "Delete Method",
    "删除值": "Delete Value",
    "删除位置": "Delete Position",
    "删除后的列表": "Deleted List",
    "排序方式": "Sort Method",
    "排序后的列表": "Sorted List",
    "打乱顺序后的列表": "Shuffled List",
    "待处理列表": "List to Process",
    "剔除元素列表": "Elements to Remove List",
    "剔除后的列表": "Filtered List",
    "反转后的列表": "Reversed List",
    "第一个列表": "First List",
    "第二个列表": "Second List",
    "合并后的列表": "Merged List",
    "去重后的列表": "Deduplicated List",
    "重复项列表": "Duplicate Items List",
    "索引": "Index",
    "长度": "Length",
    "生成随机数": "Generate Random Number",
    "四舍五入": "Round",
    "自增自减": "Increment/Decrement",
    "获取绝对值": "Get Absolute Value",
    "数学计算": "Math Calculation",
    "随机数类型": "Random Number Type",
    "随机数个数": "Random Number Count",
    "开始范围": "Start Range",
    "结束范围": "End Range",
    "生成的随机数": "Generated Random Numbers",
    "原有数据": "Original Data",
    "精度": "Precision",
    "四舍五入后的数字": "Rounded Number",
    "原数据": "Original Data",
    "自增/自减": "Increment/Decrement",
    "自增或自减的数字": "Increment/Decrement Number",
    "自增自减后的结果": "Result After Increment/Decrement",
    "原数据绝对值": "Absolute Value of Original Data",
    "绝对值": "Absolute Value",
    "运算符左侧值": "Left Operand",
    "运算符": "Operator",
    "运算符右侧值": "Right Operand",
    "返回值处理方式": "Result Handling Method",
    "四舍五入保留位数": "Round to Decimal Places",
    "计算结果": "Calculation Result",
    "文本提取内容": "Extract Content from Text",
    "文本替换内容": "Replace Content in Text",
    "列表聚合为文本": "Aggregate List to Text",
    "文本分割为列表": "Split Text to List",
    "文本合并": "Merge Text",
    "文本补齐至固定长度": "Pad Text to Fixed Length",
    "文本去除两侧空格": "Trim Text Spaces",
    "截取固定长度文本": "Extract Fixed Length Text",
    "更改文本大小写": "Change Text Case",
    "获取文本长度": "Get Text Length",
    "原文本": "Original Text",
    "提取类型": "Extract Type",
    "正则表达式": "Regular Expression",
    "仅提取第一项匹配内容": "Extract Only First Match",
    "提取内容": "Extracted Content",
    "替换类型": "Replace Type",
    "需要替换的字符串": "String to Replace",
    "用正则表达式替换": "Replace with Regular Expression",
    "替换为": "Replace With",
    "仅替换第一项匹配内容": "Replace Only First Match",
    "忽略大小写": "Ignore Case",
    "替换后的文本": "Replaced Text",
    "分隔符": "Separator",
    "聚合后的文本": "Aggregated Text",
    "文本数据": "Text Data",
    "分割后的列表": "Split List",
    "第一个文本": "First Text",
    "第二个文本": "Second Text",
    "合并类型": "Merge Type",
    "合并后的文本": "Merged Text",
    "补齐字符": "Padding Character",
    "总长度": "Total Length",
    "补齐方式": "Padding Method",
    "补齐后的文本": "Padded Text",
    "去除方式": "Trim Method",
    "去除两侧空格后的文本": "Text After Trimming Spaces",
    "截取文本": "Extract Text",
    "截取长度": "Extract Length",
    "截取类型": "Extract Type",
    "从第几个字符开始截取": "Start Extraction from Character",
    "需要检索的字符串": "String to Search",
    "截取后的文本": "Extracted Text",
    "大小写类型": "Case Type",
    "更改后的文本": "Changed Text",
    "文本长度": "Text Length",
    "获取当前时间": "Get Current Time",
    "设置时间": "Set Time",
    "时间对象转时间戳": "DateTime to Timestamp",
    "时间戳转时间对象": "Timestamp to DateTime",
    "获取时间差": "Get Time Difference",
    "输出指定格式时间文本": "Output Formatted Time Text",
    "时间格式": "Time Format",
    "当前时间对象": "Current Time Object",
    "时间对象": "Time Object",
    "日期调整方式": "Date Adjustment Method",
    "秒": "Seconds",
    "分": "Minutes",
    "时": "Hours",
    "天": "Days",
    "月": "Months",
    "年": "Years",
    "设置时间对象": "Set Time Object",
    "时间戳精度": "Timestamp Precision",
    "时间戳": "Timestamp",
    "选择时区": "Select Time Zone",
    "时间对象1": "Time Object 1",
    "时间对象2": "Time Object 2",
    "时间单位": "Time Unit",
    "时间差": "Time Difference",
    "时间文本": "Time Text",
    "数据": "Data",
    "处理": "Process",
    "转换": "Transform",
    "赋值": "assign",
    "给变量": "to variable",
    "从": "from",
    "格式": "format",
    "为": "to",
    "字符串": "string",
    "对": "for",
    "进行": "perform",
    "创建": "create",
    "一个": "a",
    "字典": "dictionary",
    "的": "of",
    "键": "key",
    "值": "value",
    "位置": "position",
    "个": "items",
    "范围": "range",
    "到": "to",
    "将": "convert",
    "按": "by",
    "中": "in",
    "和": "and",
    "以": "with",
    "对列表": "for list",
    "根据": "based on",
    "获取": "get",
    "需要": "need",
    "如": "such as",
    "可": "can",
    "填写": "fill",
    "选择": "select",
    "支持": "support",
    "用于": "used for",
    "例": "example",
    "输出": "output",
    
    # Encrypt related
    "MD5加密": "MD5 Encryption",
    "SHA加密": "SHA Encryption",
    "对称加密": "Symmetric Encryption",
    "对称解密": "Symmetric Decryption",
    "Base64编码": "Base64 Encoding",
    "Base64解码": "Base64 Decoding",
    "需要加密的字符串": "String to Encrypt",
    "加密位数": "Encryption Bits",
    "大小写选择": "Case Selection",
    "MD5加密结果": "MD5 Encryption Result",
    "SHA加密方法": "SHA Encryption Method",
    "SHA加密结果": "SHA Encryption Result",
    "加密密钥": "Encryption Key",
    "对称加密结果": "Symmetric Encryption Result",
    "需要解密的字符串": "String to Decrypt",
    "解密密钥": "Decryption Key",
    "对称解密结果": "Symmetric Decryption Result",
    "编码类型": "Encoding Type",
    "字符串数据": "String Data",
    "编码后的字符串": "Encoded String",
    "解码类型": "Decoding Type",
    "Base64字符串": "Base64 String",
    "图片保存文件夹": "Image Save Folder",
    "图片文件名": "Image File Name",
    "存在同名文件处理方式": "Handling for Existing Files",
    "解码后的字符串/图片绝对路径": "Decoded String/Image Absolute Path",
    "加密": "Encrypt",
    "解密": "Decrypt",
    "对字符串": "for string",
    "读取": "read",
    "或": "or",
    "图片文件": "image file",
    "图片": "image",
    "存储": "store",
    
    # Enterprise related
    "上传文件至共享文件夹": "Upload File to Shared Folder",
    "从共享文件夹下载文件": "Download File from Shared Folder",
    "获取共享变量": "Get Shared Variable",
    "上传文件路径": "Upload File Path",
    "上传文件结果": "Upload File Result",
    "共享文件夹文件": "Shared Folder File",
    "文件保存路径": "File Save Path",
    "下载结果": "Download Result",
    "共享变量名": "Shared Variable Name",
    "保存共享变量至": "Save Shared Variable To",
    "上传": "upload",
    "下载": "download",
    "文件": "file",
    
    # OpenAPI related
    "身份证识别": "ID Card Recognition",
    "营业执照识别": "Business License Recognition",
    "增值税发票识别": "VAT Invoice Recognition",
    "火车票识别": "Train Ticket Recognition",
    "出租车发票识别": "Taxi Invoice Recognition",
    "通用文字识别": "General Text Recognition",
    "批量处理": "Batch Processing",
    "图像文件": "Image File",
    "图像文件夹": "Image Folder",
    "输出文档": "Output Document",
    "文档输出路径": "Document Output Path",
    "文档输出文件名": "Document Output File Name",
    "身份证识别结果对象": "ID Card Recognition Result Object",
    "营业执照结果对象": "Business License Result Object",
    "增值税发票识别结果对象": "VAT Invoice Recognition Result Object",
    "火车票识别结果对象": "Train Ticket Recognition Result Object",
    "出租车发票识别结果对象": "Taxi Invoice Recognition Result Object",
    "通用文字识别结果对象": "General Text Recognition Result Object",
    "识别": "Recognition",
    "图像": "Image",
    "OCR": "OCR",
    "每次": "each time",
    "单个": "single",
    "处理": "process",
    "一份": "one",
    "默认": "default",
    "按": "by",
    "文件夹": "folder",
    "类": "type",
    "文件": "file",
    "顺序": "order",
    "依次": "sequentially",
    "保存为": "save as",
    "excel文档": "Excel document",
    "不支持": "not supported",
    "修改": "modify",
    
    # Report related
    "日志打印": "Log Print",
    "日志类型": "Log Type",
    "日志内容": "Log Content",
    "打印运行过程中输出的流变量": "Print stream variables output during execution",
    "调试": "Debug",
    "信息": "Info",
    "警告": "Warning",
    "错误": "Error",
    "打印": "print",
    
    # Script related
    "运行Python模块": "Run Python Module",
    "选择Python模块": "Select Python Module",
    "执行结果": "Execution Result",
    "运行": "run",
    "Python模块": "Python module",
    "脚本": "Script",
    "代码": "Code",
    
    # Software related
    "打开程序": "Open Program",
    "关闭程序": "Close Program",
    "Cmd命令": "Cmd Command",
    "应用程序路径": "Application Path",
    "运行参数": "Run Parameters",
    "cmd字符串": "cmd String",
    "打开": "open",
    "应用程序": "application",
    "设置": "set",
    "参数": "parameters",
    "关闭": "close",
    "程序": "program",
    "通过配置": "by configuring",
    "执行": "execute",
    "命令": "command",
    "保存至": "save to",
    
    # Verifycode related
    "通用数英验证码": "General Text Captcha",
    "通用滑块验证码": "General Slider Captcha",
    "通用点击验证码": "General Click Captcha",
    "浏览器对象": "Browser Object",
    "拾取验证码对象": "Pick Captcha Object",
    "验证码类型": "Captcha Type",
    "是否填写输入框": "Fill Input Box",
    "输入框对象": "Input Box Object",
    "识别结果": "Recognition Result",
    "背景图片对象": "Background Image Object",
    "拾取滑块对象": "Pick Slider Object",
    "是否为变速验证码": "Is Variable Speed Captcha",
    "拾取滑动图片对象": "Pick Sliding Image Object",
    "微调步长（px）": "Fine Adjustment Step (px)",
    "移动距离": "Move Distance",
    "点击图片对象": "Click Image Object",
    "指示顺序的图片相对大图的位置": "Position of Order Indicator Image Relative to Main Image",
    "验证码": "Captcha",
    "浏览器": "browser",
    "拖动": "drag",
    "滑块": "slider",
    "至": "to",
    "指定位置": "specified position",
    "拖动距离": "drag distance",
    "点击": "click",
    "对应位置": "corresponding position",
    
    # Vision related
    "点击图像": "Click Image",
    "鼠标悬浮在图像上": "Mouse Hover on Image",
    "IF 图像存在": "IF Image Exists",
    "等待图像": "Wait for Image",
    "图像输入框输入": "Image Input Box Input",
    "目标图像": "Target Image",
    "鼠标按键": "Mouse Button",
    "点击方式": "Click Method",
    "点击位置": "Click Position",
    "指定位置": "Specified Position",
    "横向平移": "Horizontal Translation",
    "纵向平移": "Vertical Translation",
    "匹配相似度": "Match Similarity",
    "鼠标移动方式": "Mouse Movement Method",
    "鼠标移动速度": "Mouse Movement Speed",
    "等待图像出现时间(秒)": "Wait Time for Image (seconds)",
    "悬浮位置": "Hover Position",
    "判断类型": "Judgment Type",
    "等待图像时间(秒)": "Wait Time for Image (seconds)",
    "等待类型": "Wait Type",
    "等待时间(秒)": "Wait Time (seconds)",
    "等待结果": "Wait Result",
    "输入方式": "Input Method",
    "输入内容": "Input Content",
    "模拟人工输入": "Simulate Manual Input",
    "输入间隔": "Input Interval",
    "图像出现": "Image Appears",
    "图像消失": "Image Disappears",
    "鼠标": "mouse",
    "检索": "search for",
    "并": "and",
    "在": "in",
    "窗口": "window",
    "界面": "interface",
    "该": "this",
    "移动": "move",
    "判断": "judge",
    "是否": "whether",
    "存在": "exists",
    "出现": "appear",
    "消失": "disappear",
    "再": "then",
    "继续": "continue",
    "流程": "process",
    "拾取": "pick",
    "以": "with",
    "超过": "exceeds",
    "该时间": "this time",
    "停止等待": "stop waiting",
    "查找": "search",
    "与": "and",
    "当前": "current",
    "页面": "page",
    "相似度": "similarity",
    "阈值": "threshold",
    "最高": "maximum",
    "匹配": "match",
    "精确度": "accuracy",
    "精准": "precise",
    "表示": "indicates",
    "界面": "interface",
    "截取": "captured",
    "完全一致": "completely identical",
    "时候": "when",
    "才能": "can",
    "成功": "succeed",
    
    # Common labels
    "是": "Yes",
    "否": "No",
    "左键": "Left Click",
    "中键": "Middle Click",
    "右键": "Right Click",
    "单击": "Single Click",
    "双击": "Double Click",
    "中心点": "Center",
    "随机位置": "Random Position",
    "匀速直线": "Constant Speed Linear",
    "模拟人工": "Simulate Manual",
    "瞬时移动": "Instant Move",
    "慢速": "Slow",
    "正常": "Normal",
    "快速": "Fast",
    "字符输入": "Character Input",
    "剪切板输入": "Clipboard Input",
    "文件形式": "File Format",
    "文本形式": "Text Format",
    "升序": "Ascending",
    "降序": "Descending",
    "整数": "Integer",
    "浮点数": "Float",
    "字符串": "String",
    "布尔值": "Boolean",
    "列表": "List",
    "字典": "Dictionary",
    "元组": "Tuple",
    "其他": "Other",
    "追加": "Append",
    "指定位置插入": "Insert at Position",
    "指定位置删除": "Delete at Position",
    "指定值删除": "Delete by Value",
    "抛出异常": "Raise Error",
    "返回默认值": "Return Default Value",
    "空列表": "Empty List",
    "相同元素列表": "Same Element List",
    "用户自定义列表": "User Defined List",
    "加": "Add",
    "减": "Subtract",
    "乘": "Multiply",
    "除": "Divide",
    "四舍五入": "Round",
    "向上取整": "Ceil",
    "向下取整": "Floor",
    "不做操作": "No Operation",
    "中国大陆手机号码": "China Mobile Number",
    "邮箱地址": "Email Address",
    "网址": "URL",
    "数字": "Number",
    "中国大陆身份证号码": "China ID Number",
    "不使用分隔符": "No Separator",
    "换行符": "Line Break",
    "空格（ ）": "Space ( )",
    "连字符（-）": "Hyphen (-)",
    "下划线（_）": "Underscore (_)",
    "自定义": "Custom",
    "右补齐": "Right Pad",
    "左补齐": "Left Pad",
    "左侧": "Left",
    "右侧": "Right",
    "两侧": "Both Sides",
    "从第一个字符开始截取": "Extract from First Character",
    "从指定位置开始截取": "Extract from Specified Position",
    "从指定字符串开始截取": "Extract from Specified String",
    "全部大写": "All Uppercase",
    "全部小写": "All Lowercase",
    "首字母大写": "Capitalize",
    "年-月-日": "Year-Month-Day",
    "年-月-日 时:分:秒": "Year-Month-Day Hour:Minute:Second",
    "年-月-日 时:分": "Year-Month-Day Hour:Minute",
    "年/月/日": "Year/Month/Day",
    "年/月/日 时:分": "Year/Month/Day Hour:Minute",
    "年/月/日 时:分:秒": "Year/Month/Day Hour:Minute:Second",
    "年月日": "YearMonthDay",
    "时:分": "Hour:Minute",
    "时:分:秒": "Hour:Minute:Second",
    "一周的第几天": "Day of Week",
    "一年的第几天": "Day of Year",
    "一年的第几周": "Week of Year",
    "保持不变": "Keep Unchanged",
    "增加时间": "Add Time",
    "减少时间": "Subtract Time",
    "秒": "Second",
    "毫秒": "Millisecond",
    "微秒": "Microsecond",
    "UTC标准时间": "UTC Standard Time",
    "本地时间": "Local Time",
    "分": "Minute",
    "时": "Hour",
    "天": "Day",
    "月": "Month",
    "年": "Year",
    "32位": "32-bit",
    "16位": "16-bit",
    "小写字母": "Lowercase",
    "大写字母": "Uppercase",
    "覆盖原有文件": "Overwrite Original File",
    "创建文件副本": "Create File Copy",
    "取消保存操作": "Cancel Save Operation",
    "其他邮箱": "Other Mailbox",
    "讯飞邮箱": "iFlytek Mailbox",
    "下": "Bottom",
    "上": "Top",
    "通用数英验证码1-4位": "General Text Captcha 1-4 digits",
    "通用数英验证码5-8位": "General Text Captcha 5-8 digits",
    "通用数英验证码（特殊)": "General Text Captcha (Special)",
}


def translate_text(text):
    """Translate Chinese text to English using the translation dictionary."""
    if not text or not isinstance(text, str):
        return text
    
    # If it's already in English (no Chinese characters), return as is
    if not re.search(r'[\u4e00-\u9fa5]', text):
        return text
    
    # Try exact match first
    if text in TRANSLATIONS:
        return TRANSLATIONS[text]
    
    # Try to build translation from parts
    result = text
    
    # Sort translations by length (longest first) to match longer phrases first
    sorted_translations = sorted(TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True)
    
    for chinese, english in sorted_translations:
        if chinese in result:
            result = result.replace(chinese, english)
    
    # If still contains significant Chinese, log it
    if re.search(r'[\u4e00-\u9fa5]{2,}', result):
        print(f"  Warning: Untranslated text: {text} -> {result}")
    
    return result


def translate_value(value):
    """Recursively translate values in config structure."""
    if isinstance(value, dict):
        return {k: translate_value(v) for k, v in value.items()}
    elif isinstance(value, list):
        return [translate_value(item) for item in value]
    elif isinstance(value, str):
        return translate_text(value)
    else:
        return value


def translate_file(filepath):
    """Translate a single config.yaml file."""
    print(f"\n{'='*60}")
    print(f"Translating: {filepath}")
    print('='*60)
    
    try:
        # Read the file
        with open(filepath, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f)
        
        # Translate
        translated_config = translate_value(config)
        
        # Write back
        with open(filepath, 'w', encoding='utf-8') as f:
            yaml.dump(translated_config, f, allow_unicode=True, sort_keys=False, default_flow_style=False)
        
        print(f"✓ Successfully translated!")
        return True
        
    except Exception as e:
        print(f"✗ Error: {e}")
        return False


def main():
    """Main function to translate all specified config files."""
    files_to_translate = [
        r"e:\astron-rpa\engine\components\astronverse-ai\config.yaml",
        r"e:\astron-rpa\engine\components\astronverse-dataprocess\config.yaml",
        r"e:\astron-rpa\engine\components\astronverse-email\config.yaml",
        r"e:\astron-rpa\engine\components\astronverse-encrypt\config.yaml",
        r"e:\astron-rpa\engine\components\astronverse-enterprise\config.yaml",
        r"e:\astron-rpa\engine\components\astronverse-openapi\config.yaml",
        r"e:\astron-rpa\engine\components\astronverse-report\config.yaml",
        r"e:\astron-rpa\engine\components\astronverse-script\config.yaml",
        r"e:\astron-rpa\engine\components\astronverse-software\config.yaml",
        r"e:\astron-rpa\engine\components\astronverse-verifycode\config.yaml",
        r"e:\astron-rpa\engine\components\astronverse-vision\config.yaml",
    ]
    
    print("\n" + "="*60)
    print("RPA Component Config Translation")
    print("="*60)
    print(f"\nTranslating {len(files_to_translate)} files...")
    print("Backups have been created with .bak extension")
    
    success_count = 0
    for filepath in files_to_translate:
        if translate_file(filepath):
            success_count += 1
    
    print("\n" + "="*60)
    print(f"Translation Complete: {success_count}/{len(files_to_translate)} files succeeded")
    print("="*60)
    print("\nPlease review the translations and check for any warnings above.")


if __name__ == "__main__":
    main()
