"""
Upload translated atom metadata to the database.
This script generates metadata from config files and uploads to the backend.
"""

import json
import os
import sys
import subprocess
from pathlib import Path
import requests


def generate_metadata_for_component(component_path):
    """Run meta.py for a component to generate JSON metadata."""
    meta_file = component_path / "meta.py"
    
    if not meta_file.exists():
        return None
    
    print(f"  Generating metadata for {component_path.name}...")
    
    try:
        # Run meta.py and capture output
        result = subprocess.run(
            [sys.executable, str(meta_file)],
            cwd=component_path,
            capture_output=True,
            text=True,
            timeout=30
        )
        
        if result.returncode == 0:
            print(f"  ✅ Generated metadata for {component_path.name}")
            return True
        else:
            print(f"  ❌ Error: {result.stderr}")
            return False
            
    except Exception as e:
        print(f"  ❌ Exception: {e}")
        return False


def upload_metadata_to_backend(api_url="http://localhost:8080"):
    """Upload generated metadata JSON files to backend."""
    # This would need the actual metadata JSON files generated by meta.py
    # and upload them via the /robot/atom/save-atomics API
    print("\n⚠️  Manual step required:")
    print("After metadata generation, you need to upload to database.")
    print("This typically happens during the build process or via admin API.")
    print(f"\nAPI endpoint: {api_url}/robot/atom/save-atomics")


def main():
    print("=" * 70)
    print("Generate and Upload Atom Metadata with English Translations")
    print("=" * 70)
    print()
    
    components_path = Path(r"e:\astron-rpa\engine\components")
    component_dirs = [d for d in components_path.iterdir() 
                     if d.is_dir() and d.name.startswith("astronverse-")]
    
    print(f"Found {len(component_dirs)} components\n")
    
    success_count = 0
    for component_dir in sorted(component_dirs):
        result = generate_metadata_for_component(component_dir)
        if result:
            success_count += 1
    
    print(f"\n✅ Generated metadata for {success_count} components")
    
    upload_metadata_to_backend()
    
    print("\n" + "=" * 70)
    print("IMPORTANT: Database Update Required")
    print("=" * 70)
    print("""
The config files have been translated, but you need to update the database.

Two options:

1. **Easiest: Rebuild the entire system**
   - This will regenerate and upload all metadata
   - Run: build.bat (from project root)

2. **Quick: Clear database and restart**
   - Stop Docker services
   - Clear the atom metadata table in MySQL
   - Restart services (they should auto-populate from config files)

3. **Manual: Use admin API (if available)**
   - Upload via /robot/atom/save-atomics endpoint
   - Or use admin panel to reload metadata

After updating the database, clear browser cache and refresh the frontend.
""")


if __name__ == "__main__":
    main()
