# -*- coding: utf-8 -*-
"""
Comprehensive translation script for all atom definitions - Version 2
Translates Chinese UI text to English for the Astron RPA workflow builder.
"""

import re

# ===========================================
# WORD-LEVEL TRANSLATIONS (applied last)
# ===========================================
WORD_TRANSLATIONS = {
    # Single character words
    "上": "up",
    "下": "down",
    "左": "left",
    "右": "right",
    "前": "forward",
    "后": "back",
    "中": "in",
    "到": "to",
    "为": "as",
    "是": "is",
    "否": "no",
    "的": "",  # possessive particle, usually not needed
    "和": "and",
    "或": "or",
    "在": "in",
    "从": "from",
    "至": "to",
    "与": "and",
    "以": "with",
    "及": "and",
    "等": "etc",
    "如": "like",
    "则": "then",
    "若": "if",
    "将": "will",
    "把": "",
    "被": "be",
    "已": "already",
    "未": "not",
    "可": "can",
    "需": "need",
    "要": "need",
    "能": "can",
    "会": "will",
    "对": "for",
    "于": "at",
    "有": "has",
    "无": "no",
    "不": "not",
    "非": "non",
    "再": "again",
    "也": "also",
    "都": "all",
    "每": "each",
    "个": "",
    "项": "item",
    "行": "row",
    "列": "column",
    "页": "page",
    "张": "",
    "条": "",
    "次": "time",
    "秒": "sec",
    "分": "min",
    "时": "hour",
    "天": "day",
    "周": "week",
    "月": "month",
    "年": "year",
    "新": "new",
    "旧": "old",
    "大": "large",
    "小": "small",
    "长": "long",
    "短": "short",
    "高": "high",
    "低": "low",
    "宽": "wide",
    "窄": "narrow",
    "快": "fast",
    "慢": "slow",
    "多": "more",
    "少": "less",
    "全": "all",
    "空": "empty",
    "满": "full",
    "真": "true",
    "假": "false",
    "开": "open",
    "关": "close",
    "启": "start",
    "停": "stop",
    "始": "start",
    "末": "end",
    "首": "first",
    "尾": "last",
    "头": "head",
    "底": "bottom",
    "顶": "top",
    "端": "end",
}

# ===========================================
# PHRASE-LEVEL TRANSLATIONS (applied first)
# ===========================================
TRANSLATIONS = {
    # ============ TITLES ============
    "大模型": "Large Language Models",
    "多轮会话": "Multi-turn Conversation",
    "单轮会话": "Single-turn Conversation",
    "知识问答": "Knowledge Q&A",
    "主题扩写": "Topic Expansion",
    "段落扩写": "Paragraph Expansion",
    "段落缩写": "Paragraph Abbreviation",
    "简历评分": "Resume Scoring",
    "职位关键词生成": "Job Keyword Generation",
    "合同要素提取": "Contract Element Extraction",
    "调用Dify工作流": "Call Dify Workflow",
    "调用Dify对话流": "Call Dify Chatflow",
    "调用星辰Agent流程": "Call XingChen Agent Flow",
    "营业执照识别": "Business License Recognition",
    "身份证识别": "ID Card Recognition",
    "增值税发票识别": "VAT Invoice Recognition",
    "火车票识别": "Train Ticket Recognition",
    "出租车发票识别": "Taxi Invoice Recognition",
    "通用文字识别": "General Text Recognition",
    "验证码": "Captcha",
    "通用数英验证码": "General Alphanumeric Captcha",
    "通用滑块验证码": "General Slider Captcha",
    "通用点击验证码": "General Click Captcha",
    "流程": "Process",
    "运行子流程": "Run Sub-process",
    "运行Python模块": "Run Python Module",
    "代码流程": "Code Flow",
    "设置变量值": "Set Variable Value",
    "日志打印": "Log Print",
    "条件判断": "Conditional",
    "IF条件": "IF Condition",
    "IF图像存在": "IF Image Exists",
    "IF文件夹存在": "IF Folder Exists",
    "IF文件存在": "IF File Exists",
    "IF窗口存在": "IF Window Exists",
    "ELSE IF条件": "ELSE IF Condition",
    "ELSE条件": "ELSE Condition",
    "循环": "Loop",
    "字典For循环": "Dictionary For Loop",
    "列表For循环": "List For Loop",
    "计数For循环": "Count For Loop",
    "循环Excel内容": "Loop Excel Content",
    "循环相似元素列表": "Loop Similar Elements",
    "While循环": "While Loop",
    "退出循环": "Exit Loop",
    "继续下次循环": "Continue Loop",
    "错误处理": "Error Handling",
    "捕获异常": "Catch Exception",
    "网页自动化": "Web Automation",
    "网页操作": "Page Operations",
    "打开浏览器": "Open Browser",
    "关闭浏览器": "Close Browser",
    "获取已打开的浏览器对象": "Get Opened Browser Objects",
    "元素是否存在": "Element Exists",
    "等待元素": "Wait for Element",
    "元素操作": "Element Operations",
    "点击元素": "Click Element",
    "获取元素文本内容": "Get Element Text",
    "获取元素文本": "Get Element Text",
    "填写输入框": "Fill Input Box",
    "获取复选框": "Get Checkbox",
    "操作复选框": "Operate Checkbox",
    "获取下拉框": "Get Dropdown",
    "操作下拉框": "Operate Dropdown",
    "拾取滑块拖拽": "Pick Slider Drag",
    "鼠标悬停在元素上": "Mouse Hover Element",
    "鼠标悬停元素": "Mouse Hover Element",
    "拾取元素截图": "Pick Element Screenshot",
    "元素位置截图": "Element Position Screenshot",
    "元素置于可视区域": "Scroll Element to View",
    "获取表格数据": "Get Table Data",
    "数据抓取": "Data Scraping",
    "获取相似元素列表": "Get Similar Elements",
    "获取元素对象": "Get Element Object",
    "获取关联元素": "Get Related Elements",
    "网页文件": "Web File",
    "设置Cookie": "Set Cookie",
    "保存用户的文件": "Save User File",
    "保存后是否关闭文件": "Close File After Save",
    "保存移动后的文件": "Save Moved File",
    "保存的Excel文件名": "Save Excel Filename",
    "保存的Excel文件": "Save Excel File",
    "保存删除文件": "Save Delete File",
    "存在文件处理方式": "Existing File Handling",
    "文件存在处理方式": "File Exists Handling",
    "选择存在文件处理方式": "Select Existing File Handling",
    "选择文件存在处理方式": "Select File Exists Handling",
    "选择或输入待读取文件路径": "Select or Input File Path to Read",
    "选择或输入文件夹目录路径": "Select or Input Folder Directory Path",
    "选择或输入待保存文件夹目录路径": "Select or Input Folder Path to Save",
    "待保存文件夹目录": "Folder to Save",
    "保存文件夹": "Save Folder",
    "选择保存文件夹路径": "Select Save Folder Path",
    "选择存储文件路径": "Select Storage File Path",
    "存储文件路径": "Storage File Path",
    "合并文件名": "Merged Filename",
    "输入合并文件名": "Input Merged Filename",
    "获取文件/文件夹(FTP)": "Get File/Folder (FTP)",
    "获取文件/文件夹": "Get File/Folder",
    "重命名FTP服务器上文件/文件夹": "Rename File/Folder on FTP Server",
    "文件名称后增加数字标识": "add number after filename",
    "图片文件名前缀": "Image Filename Prefix",
    "图片文件名": "Image Filename",
    "图像名": "Image Name",
    "变量名": "Variable Name",
    "用户名": "Username",
    "列名": "Column Name",
    "邮件箱名称": "Mailbox Name",
    "默认名称": "Default Name",
    "文件扩展名": "File Extension",
    "获取Cookie": "Get Cookie",
    "打开新网页": "Open New Page",
    "获取当前标签页ID": "Get Current Tab ID",
    "切换到已存在标签页": "Switch to Existing Tab",
    "关闭网页": "Close Page",
    "刷新当前网页": "Refresh Current Page",
    "停止加载网页": "Stop Loading Page",
    "网页前进": "Page Forward",
    "网页后退": "Page Backward",
    "网页截图": "Page Screenshot",
    "鼠标滚动网页": "Mouse Scroll Page",
    "获取网页URL": "Get Page URL",
    "获取网页标题": "Get Page Title",
    "等待页面加载完成": "Wait for Page Load",
    "文件下载": "File Download",
    "文件上传": "File Upload",
    "桌面自动化": "Desktop Automation",
    "窗口操作": "Window Operations",
    "关闭程序": "Close Program",
    "打开程序": "Open Program",
    "元素截图": "Element Screenshot",
    "置顶窗口": "Pin Window to Top",
    "关闭窗口": "Close Window",
    "调整窗口大小": "Resize Window",
    "文档处理": "Document Processing",
    "获取PDF文档页数": "Get PDF Page Count",
    "提取PDF文档文本": "Extract PDF Text",
    "合并PDF文件": "Merge PDF Files",
    "提取PDF文档图片": "Extract PDF Images",
    "抽取PDF指定页": "Extract PDF Pages",
    "提取PDF表格到Excel": "Extract PDF Table to Excel",
    "PDF页面转图片": "PDF Page to Image",
    "打开Word": "Open Word",
    "读取Word内容": "Read Word Content",
    "创建Word": "Create Word",
    "保存Word": "Save Word",
    "关闭Word": "Close Word",
    "插入文本到Word": "Insert Text to Word",
    "选择Word文本": "Select Word Text",
    "定位Word光标": "Position Word Cursor",
    "移动Word光标": "Move Word Cursor",
    "Word插入页": "Word Insert Page",
    "Word插入段落": "Word Insert Paragraph",
    "Word插入超链接": "Word Insert Hyperlink",
    "Word插入图片": "Word Insert Image",
    "Word读取表格": "Word Read Table",
    "Word插入表格": "Word Insert Table",
    "Word删除内容": "Word Delete Content",
    "Word替换内容": "Word Replace Content",
    "Word创建批注": "Word Create Comment",
    "Word删除批注": "Word Delete Comment",
    "Word导出为": "Word Export to",
    "打开Excel": "Open Excel",
    "添加Excel工作表": "Add Excel Worksheet",
    "获取已打开的Excel对象": "Get Opened Excel Objects",
    "创建Excel": "Create Excel",
    "保存Excel": "Save Excel",
    "关闭Excel": "Close Excel",
    "写入Excel": "Write to Excel",
    "读取Excel内容": "Read Excel Content",
    "设置单元格格式": "Set Cell Format",
    "复制Excel单元格": "Copy Excel Cell",
    "粘贴Excel单元格": "Paste Excel Cell",
    "删除Excel单元格": "Delete Excel Cell",
    "获取Excel工作表名称": "Get Excel Sheet Names",
    "清除Excel区域内容": "Clear Excel Range",
    "插入Excel行或列": "Insert Excel Row/Column",
    "获取Excel行数": "Get Excel Row Count",
    "获取Excel列数": "Get Excel Column Count",
    "获取Excel第一个可用行": "Get Excel First Available Row",
    "获取Excel第一个可用列": "Get Excel First Available Column",
    "设置Excel行高": "Set Excel Row Height",
    "设置Excel列宽": "Set Excel Column Width",
    "获取Excel单元格颜色": "Get Excel Cell Color",
    "合并或拆分Excel单元格": "Merge/Split Excel Cells",
    "移动Excel工作表": "Move Excel Worksheet",
    "删除Excel工作表": "Delete Excel Worksheet",
    "重命名Excel工作表": "Rename Excel Worksheet",
    "复制Excel工作表": "Copy Excel Worksheet",
    "查找或替换Excel内容": "Find/Replace Excel Content",
    "插入Excel图片": "Insert Excel Image",
    "插入Excel公式": "Insert Excel Formula",
    "创建Excel批注": "Create Excel Comment",
    "删除Excel批注": "Delete Excel Comment",
    "Excel区域文本转数字": "Excel Text to Number",
    "Excel区域数字转文本": "Excel Number to Text",
    "鼠标键盘": "Mouse & Keyboard",
    "键盘输入": "Keyboard Input",
    "鼠标点击": "Mouse Click",
    "鼠标滚动": "Mouse Scroll",
    "鼠标移动": "Mouse Move",
    "鼠标拖拽": "Mouse Drag",
    "获取鼠标位置": "Get Mouse Position",
    "键盘模拟按键": "Keyboard Simulate Key",
    "数据处理": "Data Processing",
    "数学操作": "Math Operations",
    "字符串操作": "String Operations",
    "列表操作": "List Operations",
    "字典操作": "Dictionary Operations",
    "时间操作": "Time Operations",
    "生成随机数": "Generate Random Number",
    "四舍五入": "Round Number",
    "自增自减": "Increment/Decrement",
    "获取绝对值": "Get Absolute Value",
    "数学计算": "Math Calculation",
    "文本提取内容": "Extract Text Content",
    "文本替换内容": "Replace Text Content",
    "列表聚合为文本": "List to Text",
    "文本分割为列表": "Text to List",
    "文本合并": "Merge Text",
    "文本补齐至固定长度": "Pad Text to Length",
    "文本去除两侧空格": "Trim Text Spaces",
    "截取固定长度文本": "Substring Fixed Length",
    "更改文本大小写": "Change Text Case",
    "获取文本长度": "Get Text Length",
    "JSON字符串互转": "JSON String Convert",
    "其他格式转文本": "Other Format to Text",
    "文本转其他格式": "Text to Other Format",
    "创建新列表": "Create New List",
    "清空列表": "Clear List",
    "列表插入值": "List Insert Value",
    "列表修改值": "List Modify Value",
    "获取值在列表位置": "Get Value Position in List",
    "列表删除值": "List Remove Value",
    "列表排序": "List Sort",
    "列表随机打乱顺序": "List Shuffle",
    "剔除列表中的多项": "Remove Multiple from List",
    "列表反转": "List Reverse",
    "列表合并": "List Merge",
    "列表去重": "List Remove Duplicates",
    "获取两个列表的重复项": "Get List Duplicates",
    "根据索引获取列表值": "Get List Value by Index",
    "获取列表长度": "Get List Length",
    "创建新字典": "Create New Dictionary",
    "字典设置值": "Dictionary Set Value",
    "字典删除值": "Dictionary Delete Value",
    "字典获取值": "Dictionary Get Value",
    "获取字典所有键": "Get Dictionary All Keys",
    "获取字典所有值": "Get Dictionary All Values",
    "获取当前时间": "Get Current Time",
    "设置时间": "Set Time",
    "时间对象转时间戳": "DateTime to Timestamp",
    "时间戳转时间对象": "Timestamp to DateTime",
    "获取时间差": "Get Time Difference",
    "输出指定格式时间文本": "Output Formatted Time",
    "操作系统": "Operating System",
    "文件操作": "File Operations",
    "文件夹操作": "Folder Operations",
    "压缩解压": "Compress/Decompress",
    "系统命令": "System Commands",
    "截图": "Screenshot",
    "剪切板": "Clipboard",
    "创建文件": "Create File",
    "写入文件": "Write File",
    "读取文件": "Read File",
    "复制文件": "Copy File",
    "移动文件": "Move File",
    "重命名文件": "Rename File",
    "删除文件": "Delete File",
    "查找文件": "Find File",
    "等待文件": "Wait for File",
    "获取文件编码类型": "Get File Encoding",
    "获取文件信息": "Get File Info",
    "获取文件列表": "Get File List",
    "上传文件至共享文件夹": "Upload to Shared Folder",
    "从共享文件夹下载文件": "Download from Shared Folder",
    "创建文件夹": "Create Folder",
    "打开文件夹": "Open Folder",
    "复制文件夹": "Copy Folder",
    "移动文件夹": "Move Folder",
    "重命名文件夹": "Rename Folder",
    "清空文件夹": "Clear Folder",
    "删除文件夹": "Delete Folder",
    "获取文件夹列表": "Get Folder List",
    "压缩": "Compress",
    "解压": "Decompress",
    "运行或打开": "Run or Open",
    "获取进程PID": "Get Process PID",
    "终止进程": "Terminate Process",
    "屏幕截图": "Screen Screenshot",
    "复制到剪切板": "Copy to Clipboard",
    "清空剪切板": "Clear Clipboard",
    "获取剪切板": "Get Clipboard",
    "加解密编解码": "Encryption/Encoding",
    "SHA加密": "SHA Encryption",
    "MD5加密": "MD5 Encryption",
    "对称解密": "Symmetric Decryption",
    "对称加密": "Symmetric Encryption",
    "Base64解码": "Base64 Decode",
    "Base64编码": "Base64 Encode",
    "网络": "Network",
    "邮件": "Email",
    "发送邮件": "Send Email",
    "接收邮件": "Receive Email",
    "HTTP请求": "HTTP Request",
    "HTTP下载": "HTTP Download",
    "创建FTP连接": "Create FTP Connection",
    "关闭FTP连接": "Close FTP Connection",
    "获取工作目录": "Get Work Directory",
    "切换工作目录": "Change Work Directory",
    "上传文件文件夹": "Upload File/Folder",
    "重命名文件文件夹": "Rename File/Folder",
    "下载文件文件夹": "Download File/Folder",
    "删除文件文件夹": "Delete File/Folder",
    "获取文件文件夹": "Get File/Folder",
    "CV图像": "CV Image",
    "点击图像": "Click Image",
    "鼠标悬浮在图像上": "Mouse Hover on Image",
    "等待图像": "Wait for Image",
    "图像输入框输入": "Image Input Box Input",
    "对话框": "Dialog",
    "消息提示框": "Message Dialog",
    "输入对话框": "Input Dialog",
    "选择对话框": "Select Dialog",
    "日期时间选择框": "DateTime Picker",
    "文件选择对话框": "File Select Dialog",
    "自定义对话框": "Custom Dialog",
    "自定义脚本": "Custom Script",
    "JS脚本": "JS Script",
    "卓越中心": "Excellence Center",
    "获取共享变量": "Get Shared Variable",
    "飞书": "Feishu",
    "连接到多维表格": "Connect to Multi-sheet",
    "列出记录": "List Records",
    "筛选": "Filter",
    "指定": "Specified",
    "创建记录": "Create Record",
    "更新记录": "Update Record",
    "删除记录": "Delete Record",
    "列出数据表": "List Data Tables",
    "新增数据表": "Add Data Table",
    "删除数据表": "Delete Data Table",
    "重命名数据表": "Rename Data Table",
    "列出字段": "List Fields",
    "新增字段": "Add Field",
    "更新字段": "Update Field",
    "删除字段": "Delete Field",
    "连接数据表": "Connect to Table",
    "获取工作表信息": "Get Worksheet Info",
    "设置筛选器": "Set Filter",
    "获取筛选结果": "Get Filter Result",
    "读取工作表数据": "Read Worksheet Data",
    "写入数据": "Write Data",
    
    # ============ FIELD LABELS ============
    "任务名称": "Task Name",
    "任务别名": "Task Alias",
    "浏览器对象": "Browser Object",
    "悬停元素拾取": "Hover Element Pick",
    "拾取元素": "Pick Element",
    "拾取元素数据": "Pick Element Data",
    "等待元素出现时间": "Wait for Element Timeout",
    "选择要等待页面所在的浏览器对象": "Select browser object for the page",
    "拾取鼠标要悬停的元素": "Pick the element for mouse to hover",
    "超过该时间停止等待": "Stop waiting after this time",
    "网址": "URL",
    "地址": "Address",
    "文件路径": "File Path",
    "文件夹路径": "Folder Path",
    "保存路径": "Save Path",
    "输出路径": "Output Path",
    "输入路径": "Input Path",
    "目标路径": "Target Path",
    "源路径": "Source Path",
    "新名称": "New Name",
    "新路径": "New Path",
    "文件名": "File Name",
    "文件夹名": "Folder Name",
    "工作表名": "Sheet Name",
    "工作表名称": "Sheet Name",
    "单元格": "Cell",
    "单元格区域": "Cell Range",
    "起始单元格": "Start Cell",
    "结束单元格": "End Cell",
    "行号": "Row Number",
    "列号": "Column Number",
    "行数": "Row Count",
    "列数": "Column Count",
    "起始行": "Start Row",
    "起始列": "Start Column",
    "结束行": "End Row",
    "结束列": "End Column",
    "内容": "Content",
    "文本": "Text",
    "文本内容": "Text Content",
    "输入内容": "Input Content",
    "输入文本": "Input Text",
    "输出内容": "Output Content",
    "输出文本": "Output Text",
    "变量名": "Variable Name",
    "变量值": "Variable Value",
    "变量": "Variable",
    "参数": "Parameter",
    "参数名": "Parameter Name",
    "参数值": "Parameter Value",
    "选项": "Option",
    "选择": "Select",
    "类型": "Type",
    "格式": "Format",
    "编码": "Encoding",
    "密码": "Password",
    "用户名": "Username",
    "账号": "Account",
    "主机": "Host",
    "端口": "Port",
    "超时": "Timeout",
    "超时时间": "Timeout Duration",
    "延迟": "Delay",
    "延迟时间": "Delay Time",
    "等待时间": "Wait Time",
    "间隔": "Interval",
    "间隔时间": "Interval Time",
    "重试次数": "Retry Count",
    "重试间隔": "Retry Interval",
    "最大次数": "Max Count",
    "最大数量": "Max Quantity",
    "最小值": "Min Value",
    "最大值": "Max Value",
    "默认值": "Default Value",
    "初始值": "Initial Value",
    "步长": "Step",
    "精度": "Precision",
    "小数位数": "Decimal Places",
    "宽度": "Width",
    "高度": "Height",
    "大小": "Size",
    "位置": "Position",
    "坐标": "Coordinates",
    "方向": "Direction",
    "模式": "Mode",
    "状态": "Status",
    "结果": "Result",
    "输出": "Output",
    "输入": "Input",
    "返回值": "Return Value",
    "返回结果": "Return Result",
    "元素": "Element",
    "元素对象": "Element Object",
    "元素数据": "Element Data",
    "元素列表": "Element List",
    "元素索引": "Element Index",
    "元素文本": "Element Text",
    "元素属性": "Element Attribute",
    "元素值": "Element Value",
    "目标元素": "Target Element",
    "父元素": "Parent Element",
    "子元素": "Child Element",
    "相邻元素": "Adjacent Element",
    "相似元素": "Similar Elements",
    "网页元素": "Web Element",
    "桌面元素": "Desktop Element",
    "图像元素": "Image Element",
    "拾取": "Pick",
    "点击元素数据": "Click Element Data",
    "输入框元素数据": "Input Box Element Data",
    "点击方式": "Click Method",
    "点击类型": "Click Type",
    "鼠标按钮": "Mouse Button",
    "点击次数": "Click Count",
    "双击": "Double Click",
    "单击": "Single Click",
    "右键点击": "Right Click",
    "左键": "Left Button",
    "右键": "Right Button",
    "中键": "Middle Button",
    "滚动距离": "Scroll Distance",
    "滚动方向": "Scroll Direction",
    "向上": "Upward",
    "向下": "Downward",
    "向左": "To Left",
    "向右": "To Right",
    "浏览器": "Browser",
    "浏览器类型": "Browser Type",
    "页面": "Page",
    "标签页": "Tab",
    "标签页ID": "Tab ID",
    "下载文件名": "Download Filename",
    "下载路径": "Download Path",
    "上传文件": "Upload File",
    "上传文件路径": "Upload File Path",
    "是否等待下载完成": "Wait for Download",
    "是否等待加载完成": "Wait for Load",
    "是否新标签页打开": "Open in New Tab",
    "是否无头模式": "Headless Mode",
    "是否最大化": "Maximize",
    "是否隐藏浏览器": "Hide Browser",
    "窗口": "Window",
    "窗口标题": "Window Title",
    "窗口句柄": "Window Handle",
    "窗口类名": "Window Class Name",
    "程序": "Program",
    "程序路径": "Program Path",
    "程序名称": "Program Name",
    "进程": "Process",
    "进程ID": "Process ID",
    "进程名": "Process Name",
    "Excel对象": "Excel Object",
    "Excel文件": "Excel File",
    "Excel文件路径": "Excel File Path",
    "工作簿": "Workbook",
    "工作表": "Worksheet",
    "工作表索引": "Sheet Index",
    "单元格值": "Cell Value",
    "单元格格式": "Cell Format",
    "单元格颜色": "Cell Color",
    "背景颜色": "Background Color",
    "字体颜色": "Font Color",
    "字体大小": "Font Size",
    "字体名称": "Font Name",
    "是否加粗": "Bold",
    "是否斜体": "Italic",
    "是否有表头": "Has Header",
    "是否覆盖": "Overwrite",
    "是否追加": "Append",
    "公式": "Formula",
    "批注": "Comment",
    "批注内容": "Comment Content",
    "Word对象": "Word Object",
    "Word文件": "Word File",
    "Word文件路径": "Word File Path",
    "段落": "Paragraph",
    "段落索引": "Paragraph Index",
    "页码": "Page Number",
    "书签": "Bookmark",
    "书签名称": "Bookmark Name",
    "超链接": "Hyperlink",
    "超链接地址": "Hyperlink URL",
    "图片": "Image",
    "图片路径": "Image Path",
    "表格": "Table",
    "表格索引": "Table Index",
    "表格行": "Table Row",
    "表格列": "Table Column",
    "PDF文件": "PDF File",
    "PDF文件路径": "PDF File Path",
    "页面范围": "Page Range",
    "起始页": "Start Page",
    "结束页": "End Page",
    "页数": "Page Count",
    "时间": "Time",
    "日期": "Date",
    "日期时间": "DateTime",
    "时间戳": "Timestamp",
    "时间格式": "Time Format",
    "日期格式": "Date Format",
    "毫秒": "Millisecond",
    "列表": "List",
    "列表值": "List Value",
    "列表索引": "List Index",
    "列表长度": "List Length",
    "列表项": "List Item",
    "起始索引": "Start Index",
    "结束索引": "End Index",
    "插入位置": "Insert Position",
    "排序方式": "Sort Method",
    "升序": "Ascending",
    "降序": "Descending",
    "字典": "Dictionary",
    "字典值": "Dictionary Value",
    "字典键": "Dictionary Key",
    "键": "Key",
    "值": "Value",
    "键值对": "Key-Value Pair",
    "字符串": "String",
    "文本值": "Text Value",
    "查找文本": "Find Text",
    "替换文本": "Replace Text",
    "分隔符": "Separator",
    "连接符": "Connector",
    "前缀": "Prefix",
    "后缀": "Suffix",
    "填充字符": "Padding Character",
    "填充长度": "Padding Length",
    "截取长度": "Substring Length",
    "截取起始": "Substring Start",
    "大写": "Uppercase",
    "小写": "Lowercase",
    "首字母大写": "Title Case",
    "正则表达式": "Regular Expression",
    "匹配模式": "Match Pattern",
    "提取模式": "Extract Pattern",
    "替换模式": "Replace Pattern",
    "数值": "Number",
    "整数": "Integer",
    "浮点数": "Float",
    "随机数": "Random Number",
    "最小随机数": "Min Random",
    "最大随机数": "Max Random",
    "运算符": "Operator",
    "加": "Add",
    "减": "Subtract",
    "乘": "Multiply",
    "除": "Divide",
    "取余": "Modulo",
    "幂": "Power",
    "绝对值": "Absolute Value",
    "四舍五入位数": "Round Digits",
    "加密": "Encrypt",
    "解密": "Decrypt",
    "解码": "Decode",
    "密钥": "Secret Key",
    "加密算法": "Encryption Algorithm",
    "哈希值": "Hash Value",
    "请求地址": "Request URL",
    "请求方式": "Request Method",
    "请求头": "Request Headers",
    "请求体": "Request Body",
    "请求参数": "Request Parameters",
    "响应": "Response",
    "响应状态码": "Status Code",
    "响应头": "Response Headers",
    "响应体": "Response Body",
    "FTP连接": "FTP Connection",
    "FTP对象": "FTP Object",
    "远程路径": "Remote Path",
    "本地路径": "Local Path",
    "邮件服务器": "Email Server",
    "发件人": "Sender",
    "收件人": "Recipient",
    "抄送": "CC",
    "密送": "BCC",
    "邮件主题": "Email Subject",
    "邮件正文": "Email Body",
    "邮件附件": "Email Attachment",
    "附件路径": "Attachment Path",
    "是否HTML格式": "Is HTML",
    "对话框标题": "Dialog Title",
    "提示信息": "Prompt Message",
    "提示内容": "Prompt Content",
    "按钮文本": "Button Text",
    "确定": "OK",
    "取消": "Cancel",
    "选项列表": "Option List",
    "默认选项": "Default Option",
    "输入类型": "Input Type",
    "输入提示": "Input Hint",
    "文件类型": "File Type",
    "文件过滤": "File Filter",
    "允许多选": "Allow Multiple",
    "图像": "Image",
    "图像路径": "Image Path",
    "截图区域": "Screenshot Area",
    "截图路径": "Screenshot Path",
    "相似度": "Similarity",
    "匹配度": "Match Score",
    "查找图像": "Find Image",
    "目标图像": "Target Image",
    "模板图像": "Template Image",
    "条件": "Condition",
    "条件表达式": "Condition Expression",
    "判断条件": "Judgment Condition",
    "循环条件": "Loop Condition",
    "循环变量": "Loop Variable",
    "循环次数": "Loop Count",
    "起始值": "Start Value",
    "结束值": "End Value",
    "异常处理": "Exception Handling",
    "异常类型": "Exception Type",
    "异常信息": "Exception Message",
    "子流程": "Sub-process",
    "子流程路径": "Sub-process Path",
    "子流程参数": "Sub-process Parameters",
    "Python模块": "Python Module",
    "Python模块路径": "Python Module Path",
    "脚本内容": "Script Content",
    "脚本路径": "Script Path",
    "模型": "Model",
    "模型名称": "Model Name",
    "提示词": "Prompt",
    "系统提示词": "System Prompt",
    "用户提示词": "User Prompt",
    "历史对话": "Chat History",
    "最大令牌数": "Max Tokens",
    "温度": "Temperature",
    "知识库": "Knowledge Base",
    "知识库ID": "Knowledge Base ID",
    "共享变量": "Shared Variable",
    "共享变量名": "Shared Variable Name",
    "共享变量值": "Shared Variable Value",
    "飞书对象": "Feishu Object",
    "多维表格": "Multi-sheet",
    "多维表格ID": "Multi-sheet ID",
    "数据表": "Data Table",
    "数据表ID": "Table ID",
    "记录ID": "Record ID",
    "字段": "Field",
    "字段ID": "Field ID",
    "字段名": "Field Name",
    "字段类型": "Field Type",
    "字段值": "Field Value",
    "筛选条件": "Filter Condition",
    "高级参数": "Advanced Parameters",
    "打印输出变量值": "Print Output Variable Value",
    "执行前延迟": "Delay Before Execution",
    "执行后延迟": "Delay After Execution",
    "执行异常时": "On Execution Error",
    "重试": "Retry",
    "任意值": "Any Value",
    "任何值": "Any Value",
    "布尔值": "Boolean",
    "对话框输出结果": "Dialog Output Result",
    "转文本": "To Text",
    "取整数部分": "Get Integer Part",
    "转整数": "To Integer",
    "转数值": "To Number",
    "删除两端空格": "Trim Spaces",
    "列表第": "List Item #",
    "列表倒数第": "List Item from End #",
    "的值": "'s Value",
    "字典包含元素个数": "Dictionary Element Count",
    "根目录": "Root Directory",
    "父目录": "Parent Directory",
    "文件名称": "File Name",
    "文件扩展名": "File Extension",
    "获取年份": "Get Year",
    "获取月份": "Get Month",
    "获取日": "Get Day",
    "获取小时": "Get Hour",
    "获取分钟": "Get Minute",
    "获取秒": "Get Second",
    "获取周几": "Get Weekday",
    "获取周数": "Get Week Number",
    "该网页的地址": "Page URL",
    "该网页的标题": "Page Title",
    "文件所在位置": "File Location",
    "第一个可用行": "First Available Row",
    "\u201c你好\u201d": "\u201cHello\u201d",
    "小明": "John",
    "到第": " to ",
    "对象": "Object",
    "并进入初始网址": "and navigate to URL",
    "将结果输出为浏览器对象": "output result as browser object",
    
    # ============ COMMENT DESCRIPTIONS ============
    "打开": "Open",
    "关闭": "Close",
    "获取": "Get",
    "设置": "Set",
    "创建": "Create",
    "删除": "Delete",
    "复制": "Copy",
    "粘贴": "Paste",
    "移动": "Move",
    "重命名": "Rename",
    "保存": "Save",
    "读取": "Read",
    "写入": "Write",
    "执行": "Execute",
    "运行": "Run",
    "停止": "Stop",
    "等待": "Wait",
    "查找": "Find",
    "替换": "Replace",
    "提取": "Extract",
    "插入": "Insert",
    "合并": "Merge",
    "拆分": "Split",
    "排序": "Sort",
    "过滤": "Filter",
    "转换": "Convert",
    "验证": "Verify",
    "检查": "Check",
    "判断": "Judge",
    "遍历": "Iterate",
    "跳过": "Skip",
    "继续": "Continue",
    "退出": "Exit",
    "返回": "Return",
    "调用": "Call",
    "发送": "Send",
    "接收": "Receive",
    "上传": "Upload",
    "下载": "Download",
    "连接": "Connect",
    "断开": "Disconnect",
    "登录": "Login",
    "登出": "Logout",
    "刷新": "Refresh",
    "点击": "Click",
    "选择": "Select",
    "勾选": "Check",
    "取消勾选": "Uncheck",
    "拖拽": "Drag",
    "滚动": "Scroll",
    "悬停": "Hover",
    "聚焦": "Focus",
    "模拟": "Simulate",
    "触发": "Trigger",
    
    # ============ ADDITIONAL PHRASES FROM FILE ============
    "一般为": "generally",
    "一般用于": "generally used for",
    "一般需要": "generally requires",
    "上一个兄弟元素": "previous sibling element",
    "下一个兄弟元素": "next sibling element",
    "上下移动单位": "vertical move unit",
    "上传列表": "upload list",
    "上传对象": "upload object",
    "上传对象已存在时": "when upload object exists",
    "上传文件结果": "upload file result",
    "上传至当前工作路径": "upload to current work path",
    "上模拟鼠标移动到": "simulate mouse move to",
    "下划线": "underline",
    "下创建文件": "create file under",
    "下创建文件名为": "create file named",
    "下创建文件夹": "create folder under",
    "下拉框选中内容": "dropdown selected content",
    "下方单元格上移": "cell below moves up",
    "下标位置从": "index position from",
    "下的": "under",
    "下的文件夹列表": "folder list under",
    "下载列表": "download list",
    "下载地址": "download URL",
    "下载场景": "download scenario",
    "下载对象": "download object",
    "下载对象存在时": "when download object exists",
    "下载指定": "download specified",
    "下载文件": "download file",
    "下载文件保存到": "save downloaded file to",
    "下载结果": "download result",
    "下载至": "download to",
    "下载链接地址": "download link URL",
    "不为空": "not empty",
    "不使用": "not use",
    "不使用分隔符": "without separator",
    "不保存": "not save",
    "不做操作": "no operation",
    "不允许空选状态": "no empty selection allowed",
    "不包含": "not include",
    "不包含文件扩展名": "without file extension",
    "不填写则关闭当前标签页": "close current tab if empty",
    "不存在": "not exist",
    "不存在为": "if not exist is",
    "不带扩展名": "without extension",
    "不影响网页加载": "does not affect page loading",
    "不指定自动沿用下载路径中的默认文件名": "auto use default filename from download path if not specified",
    "不支持修改": "modification not supported",
    "不等于": "not equal",
    "不能是列表": "cannot be list",
    "不输入则使用原文件名前缀": "use original filename prefix if empty",
    "不输入则使用默认文件名": "use default filename if empty",
    "不输入则默认标题为": "default title if empty",
    "不遍历子目录": "not traverse subdirectories",
    "不需加文件后缀": "no file suffix needed",
    "不需后缀名": "no extension needed",
    "不需要输入前序打开": "no need to input previous open",
    "不需要输入扩展名": "no need to input extension",
    "不需要输入百分号": "no need to input percent sign",
    "不需输入文件扩展名": "no need to input file extension",
    "两侧": "both sides",
    "两侧的空格去除": "trim spaces on both sides",
    "两端对齐": "justify",
    "个子元素": "child elements",
    "个字符": "characters",
    "个网页像素": "web pixels",
    "个随机数": "random numbers",
    "中与拾取到的元素": "with picked element in",
    "中元素": "element in",
    "中删除键为": "delete key in",
    "中剔除列表": "remove from list in",
    "中国大陆手机号码": "China mainland phone number",
    "中国大陆身份证号码": "China mainland ID number",
    "中定位光标位置": "position cursor in",
    "中工作表": "worksheet in",
    "中工作表名称": "worksheet name in",
    "中心点": "center point",
    "中执行有问题": "execution error in",
    "中执行有问题的": "problematic execution in",
    "中批注": "comment in",
    "中抓取": "scrape in",
    "中拾取输入框": "pick input box in",
    "中指定": "specify in",
    "中提取": "extract from",
    "中插入批注": "insert comment in",
    "中插入超链接": "insert hyperlink in",
    "中插入页": "insert page in",
    "中根据": "according to in",
    "中添加工作表": "add worksheet in",
    "必填": "required",
    "华文细黑": "STXihei",
    "单列": "single column",
    "英文等": "English etc",
    "适应": "adapt",
    "代表倒数第": "represents from end #",
    "为假": "is false",
    "为真": "is true",
    "单位": "unit",
    "从起始": "from start",
    "邮箱": "email",
    "从该": "from this",
    "志": "log",
    "中要": "need to in",
    "去重": "deduplicate",
    "一次": "once",
    "名称与扩展名": "name and extension",
    "顶部对齐": "top align",
    "底部对齐": "bottom align",
    "左对齐": "left align",
    "右对齐": "right align",
    "居中对齐": "center align",
    "垂直居中": "vertical center",
    "水平居中": "horizontal center",
    "一周的第几天": "day of week",
    "一年的第几周": "week of year",
    "一年的第几天": "day of year",
    "一个": "one",
    "秒钟": "seconds",
    "分钟": "minutes",
    "小时": "hours",
    "精准匹配": "exact match",
    "模糊匹配": "fuzzy match",
    "全部": "all",
    "部分": "partial",
    "可选": "optional",
    "必选": "required",
    "已选": "selected",
    "未选": "unselected",
    "已完成": "completed",
    "未完成": "incomplete",
    "已存在": "exists",
    "不存在时": "when not exists",
    "存在时": "when exists",
    "成功": "success",
    "失败": "failed",
    "错误": "error",
    "警告": "warning",
    "提示": "hint",
    "信息": "information",
    "确认": "confirm",
    "取消操作": "cancel operation",
    "确认操作": "confirm operation",
    "是否": "whether",
    "包含": "contains",
    "不包含时": "when not contains",
    "包含时": "when contains",
    "开始": "start",
    "结束": "end",
    "暂停": "pause",
    "恢复": "resume",
    "重置": "reset",
    "清除": "clear",
    "添加": "add",
    "移除": "remove",
    "修改": "modify",
    "更新": "update",
    "刷新": "refresh",
    "加载": "load",
    "保存成功": "save success",
    "保存失败": "save failed",
    "加载成功": "load success",
    "加载失败": "load failed",
    "操作成功": "operation success",
    "操作失败": "operation failed",
    "请输入": "please input",
    "请选择": "please select",
    "请确认": "please confirm",
    "无效的": "invalid",
    "有效的": "valid",
    "空的": "empty",
    "非空": "non-empty",
    "可用": "available",
    "不可用": "unavailable",
    "启用": "enable",
    "禁用": "disable",
    "显示": "show",
    "隐藏": "hide",
    "展开": "expand",
    "折叠": "collapse",
    "全选": "select all",
    "取消全选": "deselect all",
    "反选": "invert selection",
    "当前": "current",
    "目标": "target",
    "原始": "original",
    "默认": "default",
    "自定义": "custom",
    "高级": "advanced",
    "基本": "basic",
    "详细": "detailed",
    "简单": "simple",
    "复杂": "complex",
    "完整": "complete",
    "本地": "local",
    "远程": "remote",
    "在线": "online",
    "离线": "offline",
    "正常": "normal",
    "异常": "abnormal",
    "活动": "active",
    "非活动": "inactive",
    "只读": "readonly",
    "可写": "writable",
    "隐藏的": "hidden",
    "可见的": "visible",
    "必须": "must",
    "建议": "suggest",
    "允许": "allow",
    "拒绝": "deny",
    "接受": "accept",
    "忽略": "ignore",
    "跳过该": "skip this",
    "继续该": "continue this",
    "终止该": "terminate this",
    "中止该": "abort this",
    "恢复该": "resume this",
    "重试该": "retry this",
    "例如": "for example",
    "比如": "such as",
    "即": "i.e.",
    "或者": "or",
    "以及": "and",
    "但是": "but",
    "因为": "because",
    "所以": "so",
    "如果": "if",
    "那么": "then",
    "否则": "else",
    "当": "when",
    "直到": "until",
    "之前": "before",
    "之后": "after",
    "期间": "during",
    "同时": "meanwhile",
    "最后": "finally",
    "首先": "first",
    "然后": "then",
    "接下来": "next",
    "最终": "eventually",
    
    # ============ ADDITIONAL DOMAIN-SPECIFIC PHRASES ============
    "安装星火数字员工插件实现": "install Spark Digital Worker plugin to implement",
    "按文件夹类文件顺序依": "according to folder file order",
    "文件夹之间用逗号隔": "separate folders with comma",
    "副本文件夹同样存": "copy folder also exists",
    "根据岗位描述生成": "generate based on job description",
    "星火数字员工插件": "Spark Digital Worker Plugin",
    "同名文件处理方式": "same name file handling",
    "索引之间用逗号隔": "separate indexes with comma",
    "按照九宫格切割": "cut by grid",
    "批量打印文件夹": "batch print folder",
    "副本文件同样存": "copy file also exists",
    "根据您给定主题": "based on your given topic",
    "待解锁屏幕解锁": "unlock screen to unlock",
    "共享文件夹文件": "shared folder file",
    "待打印文件目录": "file directory to print",
    "文件夹目录路径": "folder directory path",
    "文件服务器提供": "file server provides",
    "之间使用逗号隔": "separate with comma",
    "盘消息方式来": "disk message method",
    "光标定位方式": "cursor positioning method",
    "外部导入方式": "external import method",
    "随机打乱顺序": "randomly shuffle",
    "根据职位描述": "based on job description",
    "文件处理方式": "file handling method",
    "自动化接口进": "automation interface",
    "自动生成名称": "auto generate name",
    "剩余数据填充": "remaining data fill",
    "设计弹窗界面": "design popup interface",
    "文件目录路径": "file directory path",
    "文档存储路径": "document storage path",
    "调整缩放比例": "adjust zoom ratio",
    "覆盖同名文件": "overwrite same name file",
    "支持精确匹配": "support exact match",
    "支持按文件夹": "support by folder",
    "支持填写负数": "support negative numbers",
    "系统屏幕解锁": "system screen unlock",
    "系统屏幕锁屏": "system screen lock",
    "命令工作目录": "command work directory",
    "之间用逗号隔": "separate with comma",
    "人工方式操作": "manual operation",
    "展示给用户进": "display to user",
    "区域数字转化": "region number conversion",
    "匹配方式切换": "match mode switch",
    "软件安装路径": "software install path",
    "文件夹目录": "folder directory",
    "源文件操作": "source file operation",
    "同名文件夹": "same name folder",
    "移入回收站": "move to recycle bin",
    "合同总金额": "contract total amount",
    "打印纸尺寸": "paper size",
    "支持覆盖原": "support overwrite original",
    "管理员身份": "admin identity",
    "身份授权码": "auth code",
    "单处理一份": "process one",
    "纵向偏移量": "vertical offset",
    "文件夹并重": "folder and re",
    "横向偏移量": "horizontal offset",
    "匹配精确度": "match accuracy",
    "待解锁屏幕": "screen to unlock",
    "九宫格任意": "grid any",
    "微軟正黑體": "Microsoft JhengHei",
    "自动使用待": "auto use pending",
    "服务商规范": "service provider spec",
    "邮件服务商的规范": "email service provider specification",
    "服务商的规范": "service provider specification",
    "你提出问题": "you ask questions",
    "使用驱动来": "use driver to",
    "使用打印机": "use printer",
    "二进制方式": "binary mode",
    "使用单引号": "use single quotes",
    "打印机打印": "printer print",
    "打印机名称": "printer name",
    "根据您给定": "based on your given",
    "服务器身份": "server identity",
    "盘符号组合": "disk symbol combo",
    "导出文件夹": "export folder",
    "文件服务器": "file server",
    "文件文件夹": "file folder",
    "自动使用原": "auto use original",
    "工作目录": "work directory",
    "配置了该": "configured this",
    "话式用户": "conversational user",
    "截取方式": "capture method",
    "焦点睡眠": "focus sleep",
    "指明顺序": "indicate order",
    "填入此处": "fill here",
    "指示顺序": "indicate order",
    "填写名称": "fill name",
    "打乱顺序": "shuffle order",
    "填写范围": "fill range",
    "调整方式": "adjust method",
    "系统自动": "system auto",
    "生成副本": "generate copy",
    "应代码块": "code block",
    "形式存储": "form storage",
    "用户文件": "user file",
    "建文件夹": "create folder",
    "锁屏操作": "lock screen operation",
    "转化原子": "convert atom",
    "重名文件": "duplicate name file",
    "设定消息": "set message",
    "辨率像素": "resolution pixels",
    "服务器": "server",
    "见": "see",
    "格": "cell",
    "软件": "software",
    "文件同名": "file same name",
    "读": "read",
    "常规": "normal",
    "文档范围": "document range",
    "华文琥珀": "STHupo",
    "编号": "number",
    "盘功": "disk func",
    "余": "remainder",
    "覆盖": "overwrite",
    "例": "example",
    "终止方式": "termination method",
    "脚本相": "script related",
    "取整": "round",
    "导出路径": "export path",
    "来源": "source",
    "原": "original",
    "者": "person",
    "视化": "visualization",
    "隶书": "LiSu",
    "表成": "table into",
    "鼠标按": "mouse press",
    "百": "hundred",
    "华文行楷": "STXingkai",
    "华文新魏": "STXinwei",
    "华文楷体": "STKaiti",
    "华文宋体": "STSong",
    "华文中宋": "STZhongsong",
    "华文仿宋": "STFangsong",
    "华文彩云": "STCaiyun",
    "微软雅黑": "Microsoft YaHei",
    "宋体": "SimSun",
    "黑体": "SimHei",
    "楷体": "KaiTi",
    "仿宋": "FangSong",
    "幼圆": "YouYuan",
    "等线": "DengXian",
    "方正舒体": "FZShuTi",
    "方正姚体": "FZYaoTi",
    "新宋体": "NSimSun",
    "仿宋体": "FangSong",
    "脚本": "script",
    "接口": "interface",
    "组件": "component",
    "模块": "module",
    "驱动": "driver",
    "插件": "plugin",
    "扩展": "extension",
    "版本": "version",
    "配置": "config",
    "环境": "environment",
    "系统": "system",
    "应用": "application",
    "服务": "service",
    "客户端": "client",
    "序列化": "serialize",
    "反序列化": "deserialize",
    "回调": "callback",
    "异步": "async",
    "同步": "sync",
    "并发": "concurrent",
    "线程": "thread",
    "进程": "process",
    "资源": "resource",
    "内存": "memory",
    "缓存": "cache",
    "数据库": "database",
    "表": "table",
    "索引": "index",
    "主键": "primary key",
    "外键": "foreign key",
    "唯一": "unique",
    "非空": "not null",
    "约束": "constraint",
    "事务": "transaction",
    "提交": "commit",
    "回滚": "rollback",
    "锁": "lock",
    "解锁": "unlock",
    "授权": "authorize",
    "认证": "authenticate",
    "权限": "permission",
    
    # ============ SPECIFIC UI PHRASES FROM SCREENSHOT ============
    "待复制文件": "File to Copy",
    "待Copy File": "File to Copy",
    "Specified目录": "Specified Directory",
    "指定目录": "Specified Directory",
    "目标目录": "Target Directory",
    "源目录": "Source Directory",
    "目录when not exists": "Directory when not exists",
    "目录不存在时": "Directory when not exists",
    "文件when exists": "File when exists",
    "文件存在时": "File when exists",
    "hint开报错": "hint and error",
    "hint并报错": "hint and error",
    "Create Folder副本": "Create Folder Copy",
    "创建文件夹副本": "Create Folder Copy",
    "任务名称": "Task Name",
    "任务别名": "Task Alias",
    "Copyback文件路径": "Copyback File Path",
    "复制后文件路径": "Copied File Path",
    "待": " to ",
    "并Save": " and Save",
    "toSpecified": " to Specified ",
    "SaveCopybackFile": " Save Copyback File ",
    "down，": " , ",
    "down, ": ", ",
    "hint并": " hint and ",
    "目录": " Directory",
    "报错": " Error",
    "副本": " Copy",
    "并": " and ",
    "判断": "Judge",
    "Judge文件": "Judge File",
    "选择文件": "Select File",
    "whether存在": "whether exists",
    "存在就Execute": "exists then Execute",
    "执行操作": "execute operation",
    "输出结果": "output result",
    "就": " then ",
    "，并": ", and ",
    "，": ", ",
    "。": ".",
    "则": " then ",
    "进行": " perform ",
    "完成": "complete",
    "指定": "specified",
    "您": "your",
    "您的": "your",
    "我们": "we",
    "它": "it",
    "该": "this",
    "这个": "this",
    "那个": "that",
    "某个": "some",
    "任何": "any",
    "每个": "each",
    "所有": "all",
    "其他": "other",
    "另一个": "another",
    "同一个": "same",
    "不同": "different",
    "相同": "same",
    "类似": "similar",
    "原文件": "original file",
    "新文件": "new file",
    "源文件": "source file",
    "目标文件": "target file",
    "拷贝文件": "copy file",
    "备份文件": "backup file",
    "临时文件": "temp file",
    "输出文件": "output file",
    "输入文件": "input file",
    "配置文件": "config file",
    "日志文件": "log file",
    "数据文件": "data file",
    "文本文件": "text file",
    "图片文件": "image file",
    "音频文件": "audio file",
    "视频文件": "video file",
    "压缩文件": "archive file",
    "可执行文件": "executable file",
    
    # ============ MORE SPECIFIC PHRASES ============
    "你提出问题": "you ask questions",
    "单处理一份": "process one at a time",
    "使用隐私": "use privacy",
    "匹配范围": "match range",
    "运行组件": "run component",
    "数字递增": "number increment",
    "选择组件": "select component",
    "文档范围": "document range",
    "定位方式": "positioning method",
    "自动调整": "auto adjust",
    "保留位数": "decimal places to keep",
    "按文件夹": "by folder",
    "根据简历": "based on resume",
    "文件夹彻": "folder completely",
    "智联招聘": "Zhaopin",
    "匹配方式": "match method",
    "补齐方式": "padding method",
    "改变字体": "change font",
    "职位描述": "job description",
    "职位名称": "job title",
    "超过数据": "exceed data",
    "直接存储": "direct storage",
    "合同名称": "contract name",
    "使用此网": "use this web",
    "文件夹存": "folder exists",
    "科学记数": "scientific notation",
    "合同签订": "contract signing",
    "拖动持续": "drag duration",
    "数字标识": "number identifier",
    "拖动距离": "drag distance",
    "合同方式": "contract method",
    "限制标题": "limit title",
    "盘辅助按": "disk auxiliary key",
    "人工方式": "manual method",
    "编辑范围": "edit range",
    "操作自动": "auto operation",
    "文件形式": "file format",
    "补齐字符": "padding character",
    "营业执照": "business license",
    "文档名称": "document name",
    "精确匹配": "exact match",
    "鼠标悬浮": "mouse hover",
    "简历匹配": "resume match",
    "支持字母": "support letters",
    "操作鼠标": "operate mouse",
    "处理方式": "processing method",
    "编辑区域": "edit area",
    "顺序匹配": "sequential match",
    "子文件夹": "subfolder",
    "字符数量": "character count",
    "付款方式": "payment method",
    "批量处理": "batch process",
    "匹配数量": "match count",
    "招聘网站": "recruitment website",
    "生成答案": "generate answer",
    "操作方式": "operation method",
    "匀速直线": "uniform linear",
    "写更改": "write changes",
    "岗位评": "position evaluation",
    "粗斜体": "bold italic",
    "范围还": "range also",
    "单匹配": "single match",
    "剪贴板": "clipboard",
    "区域按": "area by",
    "文件位": "file location",
    "内操作": "internal operation",
    "辅助按": "auxiliary key",
    "包名称": "package name",
    "箱名称": "box name",
    "甲方银": "Party A bank",
    "使用源": "use source",
    "框标题": "box title",
    "计数且": "count and",
    "文件所": "file location",
    "超过最": "exceed maximum",
    "示第一": "show first",
    "自增还": "increment also",
    "工作流": "workflow",
    "填写翻": "fill translation",
    "来辅助": "to assist",
    "标数量": "mark count",
    "补齐总": "padding total",
    "出现跨": "occur across",
    "纸尺寸": "paper size",
    "转元组": "to tuple",
    "自动换": "auto wrap",
    "支持单": "support single",
    "标题所": "title location",
    "乙方银": "Party B bank",
    "连字符": "hyphen",
    "抓取总": "scrape total",
    "位之间": "between positions",
    "一指令": "one instruction",
    "生成整": "generate entire",
    "合同标": "contract mark",
    "方式来": "method to",
    "续操作": "continue operation",
    "源代码": "source code",
    "选择器": "selector",
    "输入选择": "input selection",
    "选择路径": "select path",
    "必填项": "required field",
    "键盘按": "keyboard press",
    "获取图像": "get image",
    "图像数据": "image data",
    "图像位置": "image position",
    "坐标偏移": "coordinate offset",
    "偏移量": "offset",
    "像素点": "pixel",
    "像素值": "pixel value",
    "最大重试": "max retry",
    "重试延迟": "retry delay",
    "执行结果": "execution result",
    "执行状态": "execution status",
    "执行时间": "execution time",
    "执行日志": "execution log",
    "调试信息": "debug info",
    "调试模式": "debug mode",
    "调试日志": "debug log",
    "信息级别": "info level",
    "日志级别": "log level",
    "日志输出": "log output",
    "日志格式": "log format",
    "日志路径": "log path",
    "日志名称": "log name",
    "日志内容": "log content",
    "消息内容": "message content",
    "消息标题": "message title",
    "消息类型": "message type",
    "消息格式": "message format",
    "通知内容": "notification content",
    "通知标题": "notification title",
    "提示文字": "tooltip text",
    "提示信息": "hint message",
    "提示框": "tooltip",
    "确认框": "confirm box",
    "警告框": "alert box",
    "错误框": "error box",
    "对话框类型": "dialog type",
    "按钮类型": "button type",
    "按钮名称": "button name",
    "按钮文字": "button text",
    "确定按钮": "OK button",
    "取消按钮": "Cancel button",
    "关闭按钮": "Close button",
    "下一步": "Next",
    "上一步": "Previous",
    "完成按钮": "Finish button",
    "提交按钮": "Submit button",
    "重置按钮": "Reset button",
    "浏览按钮": "Browse button",
    "选择按钮": "Select button",
    "添加按钮": "Add button",
    "删除按钮": "Delete button",
    "编辑按钮": "Edit button",
    "保存按钮": "Save button",
    "取消编辑": "Cancel edit",
    "确认删除": "Confirm delete",
    "确认保存": "Confirm save",
    "确认提交": "Confirm submit",
    "确认关闭": "Confirm close",
    "确认退出": "Confirm exit",
    "正在处理": "Processing",
    "正在加载": "Loading",
    "正在保存": "Saving",
    "正在删除": "Deleting",
    "正在上传": "Uploading",
    "正在下载": "Downloading",
    "正在执行": "Executing",
    "正在连接": "Connecting",
    "已完成": "Completed",
    "已取消": "Cancelled",
    "已保存": "Saved",
    "已删除": "Deleted",
    "已上传": "Uploaded",
    "已下载": "Downloaded",
    "已连接": "Connected",
    "已断开": "Disconnected",
    "网页地址": "web address",
    "网址输入": "URL input",
    "网页内容": "web content",
    "网页元素": "web element",
    "页面元素": "page element",
    "页面内容": "page content",
    "页面标题": "page title",
    "页面地址": "page address",
    "页面加载": "page load",
    "页面刷新": "page refresh",
    "页面跳转": "page redirect",
    "新窗口": "new window",
    "新标签": "new tab",
    "当前窗口": "current window",
    "当前标签": "current tab",
    "当前页面": "current page",
    "父窗口": "parent window",
    "子窗口": "child window",
    "弹出窗口": "popup window",
    "模态窗口": "modal window",
    "非模态窗口": "non-modal window",
    "窗口句柄": "window handle",
    "窗口标题": "window title",
    "窗口大小": "window size",
    "窗口位置": "window position",
    "窗口状态": "window state",
    "最大化窗口": "maximize window",
    "最小化窗口": "minimize window",
    "还原窗口": "restore window",
    "关闭所有": "close all",
    "新建窗口": "new window",
    "切换窗口": "switch window",
    "激活窗口": "activate window",
    "前台窗口": "foreground window",
    "后台窗口": "background window",
    "等待窗口": "wait for window",
    "查找窗口": "find window",
    "定位元素": "locate element",
    "查找元素": "find element",
    "等待出现": "wait to appear",
    "等待消失": "wait to disappear",
    "等待可见": "wait visible",
    "等待可点击": "wait clickable",
    "等待加载": "wait for load",
    "等待完成": "wait for completion",
    "超时设置": "timeout setting",
    "轮询间隔": "polling interval",
    "最大等待": "max wait",
    "等待超时": "wait timeout",
    "角色": "role",
    "用户": "user",
    "管理": "manage",
    "后台": "backend",
    "前台": "frontend",
    "界面": "interface",
    "控件": "control",
    "布局": "layout",
    "样式": "style",
    "主题": "theme",
    "图标": "icon",
    "按钮": "button",
    "标签": "label",
    "输入框": "input box",
    "下拉框": "dropdown",
    "复选框": "checkbox",
    "单选框": "radio",
    "开关": "switch",
    "滑块": "slider",
    "进度条": "progress bar",
    "表单": "form",
    "表头": "header",
    "表尾": "footer",
    "菜单": "menu",
    "工具栏": "toolbar",
    "状态栏": "status bar",
    "导航": "navigation",
    "面包屑": "breadcrumb",
    "分页": "pagination",
    "树形": "tree",
    "网格": "grid",
    "卡片": "card",
    "弹窗": "popup",
    "提示框": "tooltip",
    "通知": "notification",
    "消息": "message",
    "日志": "log",
    "调试": "debug",
    "测试": "test",
    "发布": "release",
    "部署": "deploy",
    "备份": "backup",
    "恢复": "restore",
    "导入": "import",
    "导出": "export",
    "打印": "print",
    "预览": "preview",
    "缩放": "zoom",
    "旋转": "rotate",
    "翻转": "flip",
    "裁剪": "crop",
    "调整大小": "resize",
    "拖放": "drag and drop",
    "复制粘贴": "copy paste",
    "剪切": "cut",
    "撤销": "undo",
    "重做": "redo",
    "搜索": "search",
    "排列": "arrange",
    "对齐": "align",
    "分组": "group",
    "取消分组": "ungroup",
    "锁定": "lock",
    "解锁定": "unlock",
    "置顶": "bring to front",
    "置底": "send to back",
    "向前": "bring forward",
    "向后": "send backward",
    "居中": "center",
    "分布": "distribute",
    "间距": "spacing",
    "边距": "margin",
    "内边距": "padding",
    "边框": "border",
    "圆角": "corner radius",
    "阴影": "shadow",
    "透明度": "opacity",
    "渐变": "gradient",
    "填充": "fill",
    "描边": "stroke",
    "线条": "line",
    "曲线": "curve",
    "箭头": "arrow",
    "形状": "shape",
    "矩形": "rectangle",
    "圆形": "circle",
    "椭圆": "ellipse",
    "多边形": "polygon",
    "三角形": "triangle",
    "星形": "star",
    "心形": "heart",
    "云形": "cloud",
    "气泡": "bubble",
    "注释": "annotation",
    "链接": "link",
    "锚点": "anchor",
    "路径": "path",
    "节点": "node",
    "连接": "connect",
    "分支": "branch",
    "终点": "endpoint",
    "起点": "starting point",
    "航向": "heading",
    "角度": "angle",
    "弧度": "radian",
    "度": "degree",
    "比例": "ratio",
    "缩放比": "scale",
    "放大": "zoom in",
    "缩小": "zoom out",
    "适合屏幕": "fit screen",
    "实际大小": "actual size",
    "全屏": "fullscreen",
    "窗口化": "windowed",
    "最小化": "minimize",
    "最大化": "maximize",
    "标准": "standard",
    "紧凑": "compact",
    "宽松": "relaxed",
    "自适应": "adaptive",
    "响应式": "responsive",
    "固定": "fixed",
    "流式": "fluid",
    "弹性": "flexible",
    "绝对": "absolute",
    "相对": "relative",
    "静态": "static",
    "动态": "dynamic",
    "平铺": "tile",
    "堆叠": "stack",
    "重叠": "overlap",
    "交叉": "intersect",
    "联合": "union",
    "差集": "difference",
    "交集": "intersection",
    "补集": "complement",
    "空集": "empty set",
    "子集": "subset",
    "超集": "superset",
    "映射": "mapping",
    "投影": "projection",
    "变换": "transform",
    "平移": "translate",
    "旋转": "rotate",
    "倾斜": "skew",
    "镜像": "mirror",
    "反转": "invert",
    "归一化": "normalize",
    "标准化": "standardize",
    "量化": "quantize",
    "采样": "sample",
    "插值": "interpolate",
    "外推": "extrapolate",
    "平滑": "smooth",
    "锐化": "sharpen",
    "模糊": "blur",
    "噪声": "noise",
    "纹理": "texture",
    "图案": "pattern",
    "背景": "background",
    "前景": "foreground",
    "遮罩": "mask",
    "蒙版": "mask layer",
    "图层": "layer",
    "通道": "channel",
    "混合": "blend",
    "叠加": "overlay",
    "正片叠底": "multiply",
    "滤色": "screen",
    "柔光": "soft light",
    "强光": "hard light",
    "差值": "difference",
    "排除": "exclusion",
    "色相": "hue",
    "饱和度": "saturation",
    "明度": "brightness",
    "亮度": "lightness",
    "对比度": "contrast",
    "曝光": "exposure",
    "高光": "highlight",
    "暗调": "shadow",
    "中间调": "midtone",
    "色阶": "levels",
    "曲线": "curves",
    "色彩平衡": "color balance",
    "色调": "tone",
    "白平衡": "white balance",
    "色温": "color temperature",
    "鲜艳度": "vibrance",
    "去色": "desaturate",
    "黑白": "black and white",
    "棕褐色": "sepia",
    "负片": "negative",
    "二值化": "binarize",
    "灰度": "grayscale",
    "反相": "invert",
    "色彩映射": "color map",
    "假彩色": "false color",
    "伪彩色": "pseudo color",
    "热力图": "heatmap",
    "等高线": "contour",
    "矢量化": "vectorize",
    "栅格化": "rasterize",
    "像素化": "pixelate",
    "马赛克": "mosaic",
    "晶格化": "crystallize",
    "碎片化": "fragment",
    "扭曲": "distort",
    "液化": "liquify",
    "膨胀": "expand",
    "收缩": "contract",
    "波纹": "ripple",
    "漩涡": "swirl",
    "球面化": "spherize",
    "挤压": "pinch",
    "拉伸": "stretch",
    "压缩": "compress",
    "解压缩": "decompress",
    "打包": "pack",
    "解包": "unpack",
    "归档": "archive",
    "解档": "unarchive",
    "序号": "serial number",
    "批次": "batch",
    "队列": "queue",
    "堆": "heap",
    "栈": "stack",
    "链表": "linked list",
    "数组": "array",
    "哈希表": "hash table",
    "集合": "set",
    "映射表": "map",
    "有序": "ordered",
    "无序": "unordered",
    "升序排列": "ascending order",
    "降序排列": "descending order",
    "随机排列": "random order",
    "自然排序": "natural sort",
    "字母排序": "alphabetical sort",
    "数字排序": "numeric sort",
    "时间排序": "time sort",
    "大小排序": "size sort",
    "类型排序": "type sort",
    "分类": "category",
    "标记": "tag",
    "属性": "attribute",
    "特性": "feature",
    "功能": "function",
    "方法": "method",
    "事件": "event",
    "监听": "listen",
    "触发器": "trigger",
    "处理器": "handler",
    "回调函数": "callback function",
    "闭包": "closure",
    "作用域": "scope",
    "上下文": "context",
    "实例": "instance",
    "原型": "prototype",
    "继承": "inherit",
    "多态": "polymorphism",
    "封装": "encapsulation",
    "抽象": "abstraction",
    "接口实现": "interface implementation",
    "泛型": "generic",
    "模板": "template",
    "宏": "macro",
    "常量": "constant",
    "枚举": "enum",
    "结构体": "struct",
    "联合体": "union",
    "类": "class",
    "子类": "subclass",
    "父类": "parent class",
    "基类": "base class",
    "派生类": "derived class",
    "抽象类": "abstract class",
    "接口类": "interface class",
    "工厂类": "factory class",
    "单例": "singleton",
    "观察者": "observer",
    "发布者": "publisher",
    "订阅者": "subscriber",
    "中介者": "mediator",
    "代理": "proxy",
    "装饰器": "decorator",
    "适配器": "adapter",
    "桥接器": "bridge",
    "组合": "composition",
    "聚合": "aggregation",
    "依赖": "dependency",
    "注入": "injection",
    "控制反转": "inversion of control",
    "依赖注入": "dependency injection",
    "服务定位": "service locator",
    "工厂方法": "factory method",
    "抽象工厂": "abstract factory",
    "建造者": "builder",
    "原型模式": "prototype pattern",
    "单例模式": "singleton pattern",
    "适配器模式": "adapter pattern",
    "桥接模式": "bridge pattern",
    "组合模式": "composite pattern",
    "装饰模式": "decorator pattern",
    "外观模式": "facade pattern",
    "享元模式": "flyweight pattern",
    "代理模式": "proxy pattern",
    "责任链": "chain of responsibility",
    "命令模式": "command pattern",
    "解释器": "interpreter",
    "迭代器": "iterator",
    "中介者模式": "mediator pattern",
    "备忘录": "memento",
    "观察者模式": "observer pattern",
    "状态模式": "state pattern",
    "策略模式": "strategy pattern",
    "模板方法": "template method",
    "访问者": "visitor",
    
    # ============ REMAINING PHRASES BATCH 3 ============
    "滑动": "slide",
    "网银": "online banking",
    "毫米": "millimeter",
    "普通": "normal",
    "形式": "format",
    "弹出": "popup",
    "检索": "retrieve",
    "任一": "any one",
    "解析": "parse",
    "具体": "specific",
    "一些": "some",
    "批量": "batch",
    "自动": "auto",
    "导致": "cause",
    "指令": "instruction",
    "字节": "byte",
    "转置": "transpose",
    "回答": "answer",
    "拖动": "drag",
    "问题": "question",
    "实际": "actual",
    "抓取": "scrape",
    "设计": "design",
    "华文": "STXi",
    "乙方": "Party B",
    "更改": "change",
    "份数": "copies",
    "身份": "identity",
    "电脑": "computer",
    "变速": "speed",
    "文档": "document",
    "相识": "recognize",
    "话聊": "chat",
    "角横": "corner",
    "包括": "include",
    "体系": "system",
    "微调": "fine tune",
    "组件": "component",
    "名称": "name",
    "编辑": "edit",
    "单词": "word",
    "保持": "keep",
    "候才": "then",
    "重名": "duplicate",
    "计算": "calculate",
    "记录": "record",
    "兄弟": "sibling",
    "数量": "count",
    "请提": "please provide",
    "视频": "video",
    "切换": "switch",
    "截屏": "screenshot",
    "补齐": "pad",
    "请求": "request",
    "数点": "decimal point",
    "盘逐": "disk sequential",
    "画像": "portrait",
    "区域": "area",
    "反之": "otherwise",
    "轨道": "track",
    "扮演": "role play",
    "抽取": "extract",
    "答案": "answer",
    "水平": "horizontal",
    "方式": "method",
    "二进制": "binary",
    "捷函数": "shortcut function",
    "范围内": "within range",
    "应文件": "apply file",
    "纸尺寸": "paper size",
    "视区域": "view area",
    "商规范": "business spec",
    "文件夹": "folder",
    "标数量": "mark count",
    "按像素": "by pixel",
    "按文件": "by file",
    "内出现": "appear in",
    "整文档": "whole document",
    "单匹配": "single match",
    "文件存": "file exists",
    "文件彻": "file completely",
    "細明置": "MingLiU",
    "应区域": "apply area",
    "补齐总": "pad total",
    "图形库": "graphics library",
    "建文件": "create file",
    "使用此": "use this",
    "整屏幕": "full screen",
    "細明體": "MingLiU",
    "使用": "use",
    "按钮": "button",
    "字": "character",
    "元": "element",
    "单": "single",
    "双": "double",
    "夹": "folder",
    "窗": "window",
    "框": "box",
    "盒": "box",
    "件": "file",
    "本": "book",
    "簿": "book",
    "帐": "account",
    "账": "account",
    "册": "volume",
    "集": "collection",
    "库": "repository",
    "表格": "table",
    "文本": "text",
    "内容": "content",
    "格式": "format",
    "数据": "data",
    "信息": "info",
    "属性": "attribute",
    "参数": "parameter",
    "选项": "option",
    "操作": "operation",
    "处理": "process",
    "执行": "execute",
    "功能": "function",
    "程序": "program",
    "应用": "application",
    "系统": "system",
    "环境": "environment",
    "设置": "setting",
    "配置": "configuration",
    "安装": "install",
    "卸载": "uninstall",
    "启动": "start",
    "停止": "stop",
    "运行": "run",
    "暂停": "pause",
    "继续": "continue",
    "取消": "cancel",
    "确定": "confirm",
    "完成": "complete",
    "结束": "end",
    "退出": "exit",
    "返回": "return",
    "下一步": "next",
    "上一步": "back",
    "跳过": "skip",
    "重试": "retry",
    "帮助": "help",
    "关于": "about",
    "版本": "version",
    "更新": "update",
    "检查": "check",
    "验证": "verify",
    "测试": "test",
    "调试": "debug",
    "日志": "log",
    "错误": "error",
    "警告": "warning",
    "成功": "success",
    "失败": "failed",
    "正在": "processing",
    "已完成": "completed",
    "未完成": "incomplete",
    "等待中": "waiting",
    "队列中": "in queue",
    "已取消": "cancelled",
    "已暂停": "paused",
    
    # ============ REMAINING PHRASES BATCH 4 ============
    "选择组件": "select component",
    "运行组件": "run component",
    "盘辅助": "keyboard assist",
    "你提出": "you ask",
    "甲方": "Party A",
    "计数": "count",
    "存储": "storage",
    "注意": "note",
    "第几": "which",
    "版式": "layout",
    "讯飞": "iFlytek",
    "效果": "effect",
    "编组": "group",
    "焦点": "focus",
    "连续": "continuous",
    "颜色": "color",
    "光标": "cursor",
    "弹起": "release",
    "而增": "increase",
    "一份": "one copy",
    "斜体": "italic",
    "进入": "enter",
    "携带": "carry",
    "纵向": "vertical",
    "顺序": "order",
    "另存": "save as",
    "整型": "integer",
    "调整": "adjust",
    "话式": "conversational",
    "一致": "consistent",
    "定位": "locate",
    "星辰": "Xingchen",
    "出现": "appear",
    "任务": "task",
    "直接": "direct",
    "税额": "tax amount",
    "随机": "random",
    "终止": "terminate",
    "二维": "2D",
    "通用": "general",
    "粗体": "bold",
    "极速": "fast",
    "内置": "built-in",
    "桌面": "desktop",
    "填写": "fill",
    "精确": "precise",
    "人工": "manual",
    "职位": "position",
    "重复": "repeat",
    "像素": "pixel",
    "实现": "implement",
    "范围": "range",
    "消失": "disappear",
    "第一": "first",
    "货币": "currency",
    "匹配": "match",
    "生成": "generate",
    "转化": "convert",
    "建立": "establish",
    "外部": "external",
    "按照": "according to",
    "捕获": "capture",
    "位数": "digits",
    "之间": "between",
    "父级": "parent",
    "横向": "horizontal",
    "定义": "define",
    "鼠标": "mouse",
    "详情": "details",
    "限制": "limit",
    "持续": "duration",
    "屏幕": "screen",
    "命令": "command",
    "缩写": "abbreviation",
    "某些": "certain",
    "引用": "reference",
    "递增": "increment",
    "合同": "contract",
    "支持": "support",
    "根据": "based on",
    "猎聘": "Liepin",
    "激活": "activate",
    "维持": "maintain",
    "正文": "body text",
    "识别": "recognize",
    "扩写": "expand",
    "第二": "second",
    "悬浮": "hover",
    "垂直": "vertical",
    "控制": "control",
    "过程": "process",
    "随着": "as",
    "抛出": "throw",
    "通常": "usually",
    "音频": "audio",
    "税率": "tax rate",
    "角纵": "corner vertical",
    "银行": "bank",
    "账号": "account number",
    "金额": "amount",
    "总额": "total amount",
    "日期": "date",
    "甲乙": "Party A B",
    "双方": "both parties",
    "签订": "sign",
    "起止": "start end",
    "有效期": "validity period",
    "简历": "resume",
    "岗位": "position",
    "评分": "score",
    "关键词": "keywords",
    "描述": "description",
    "要素": "elements",
    "交付": "deliver",
    "付款": "payment",
    "期限": "deadline",
    "条款": "terms",
    "编号": "number",
    "标题": "title",
    "摘要": "summary",
    "内容": "content",
    "正文": "body",
    "附件": "attachment",
    "签名": "signature",
    "印章": "seal",
    "备注": "remarks",
    "发票": "invoice",
    "税号": "tax ID",
    "开票": "issue invoice",
    "验收": "acceptance",
    "确认": "confirm",
    "审批": "approval",
    "审核": "review",
    "提交": "submit",
    "撤回": "withdraw",
    "驳回": "reject",
    "通过": "pass",
    "拒绝": "reject",
    "同意": "agree",
    "反对": "disagree",
    "意见": "opinion",
    "建议": "suggestion",
    "反馈": "feedback",
    "评论": "comment",
    "评价": "evaluation",
    "等级": "level",
    "分数": "score",
    "百分比": "percentage",
    "比率": "ratio",
    "总计": "total",
    "合计": "subtotal",
    "平均": "average",
    "最高": "highest",
    "最低": "lowest",
    "最新": "latest",
    "最早": "earliest",
    "最近": "recent",
    "统计": "statistics",
    "汇总": "summary",
    "报表": "report",
    "图表": "chart",
    "折线图": "line chart",
    "柱状图": "bar chart",
    "饼图": "pie chart",
    "散点图": "scatter plot",
    "面积图": "area chart",
    "雷达图": "radar chart",
    "仪表盘": "dashboard",
    "趋势": "trend",
    "分析": "analysis",
    "预测": "prediction",
    "建模": "modeling",
    "训练": "training",
    "推理": "inference",
    "评估": "evaluation",
    "优化": "optimization",
    "调参": "tuning",
    "超参": "hyperparameter",
    "学习率": "learning rate",
    "迭代": "iteration",
    "轮次": "epoch",
    "批次大小": "batch size",
    "损失": "loss",
    "准确率": "accuracy",
    "精确率": "precision",
    "召回率": "recall",
    "文件名称": "File Name",
    "变量名称": "Variable Name",
    "文件名": "Filename",
    "单独文件名": "Individual Filename",
    "同名文件处理方式": "Same Name File Handling",
    "表格文件名": "Table Filename",
    "输入扩展名": "Input Extension",
    "导出文件名": "Export Filename",
    "新文件名称": "New Filename",
    "同名文件夹": "Same Name Folder",
    "填写图片名": "Fill Image Name",
    "输入文件名": "Input Filename",
    "保存文件名": "Save Filename",
    "文件名之间": "Between Filenames",
    "工作表名称": "Worksheet Name",
    "重名保存方式": "Duplicate Name Save Method",
    "图片名称": "Image Name",
    "输入保存文件名": "Input Save Filename",
    "重命名对象存在时": "When Renamed Object Exists",
    "待下载文件夹": "Folder to Download",
    "华文细黑": "STXihei",
    "Excel文件名": "Excel Filename",
    "重命名文件夹": "Rename Folder",
    "新建文件夹已存在时": "When New Folder Exists",
    "文件选择对话框": "File Selection Dialog",
    "重命名文件夹路径": "Rename Folder Path",
    "移动后的文件路径": "Moved File Path",
    "应用程序文件路径": "Application File Path",
    "获取文件信息": "Get File Info",
    "创建文件名为": "Create Filename As",
    "文件保存目录": "File Save Directory",
    "设置文件保存目录不存在时": "Set File Save Directory When Not Exists",
    "输入文件保存目录": "Input File Save Directory",
    "选择保存文件夹路径": "Select Save Folder Path",
    "图片保存文件夹": "Image Save Folder",
    "保存文件夹路径": "Save Folder Path",
    "保存文件路径": "Save File Path",
    "保存文件名": "Save Filename",
    "输入保存文件名": "Input Save Filename",
    "移动后文件夹路径": "Moved Folder Path",
    "保存移动后文件夹路径": "Save Moved Folder Path",
    "保存文件夹列表至变量": "Save Folder List to Variable",
    "保存文件列表至变量": "Save File List to Variable",
    "重命名后的文件夹路径": "Renamed Folder Path",
    "重命名后的文件路径": "Renamed File Path",
    "复制后的文件夹路径": "Copied Folder Path",
    "文件选择对话框": "File Selection Dialog",
    "文件夹已存在时": "When Folder Exists",
    "文件已存在时": "When File Exists",
    "新建文件夹路径": "New Folder Path",
    "创建的文件夹路径": "Created Folder Path",
    "获取的文件夹列表": "Retrieved Folder List",
    "文件彻底删除": "Permanently Delete File",
    "移入回收站": "Move to Recycle Bin",
    "文档输出路径": "Document Output Path",
    "PDF文件名": "PDF Filename",
    "文件名包含": "Filename Contains",
    "查找文件名": "Find Filename",
    "名称/扩展名": "Name/Extension",
    "Excel文件名": "Excel Filename",
    "键名": "Key Name",
    "用于提取中文": "use at Extract Chinese",
    "用于提取数字": "use at Extract numbers",
    "用于提取英文": "use at Extract English",
    "提取中文": "Extract Chinese",
    "提取数字": "Extract numbers",
    "提取英文": "Extract English",
    "中文": "Chinese",
    "全文": "Full Document",
    "整文": "Entire Document",
    "正文": "Body Text",
    "文件": "File",
    "无需输入文件扩展名": "no need to input file extension",
    "文件扩展名": "File Extension",
    "名称与扩展名": "Name and Extension",
    "不带扩展名": "without extension",
    "带扩展名": "with extension",
    "不需要输入扩展名": "no need to input extension",
    "系统会自动添加扩展名": "system will auto add extension",
    "系统建议打开显示扩展名": "system suggests showing extension",
    "可以带或不带扩展名": "can be with or without extension",
    "文件名称及扩展名": "filename and extension",
    "显示扩展名": "show extension",
    "不需输入文件扩展名": "no need to input file extension",
    "默认扩展名": "default extension",
    "文档输出文件名": "Document Output Filename",
    "系统命令": "System Command",
    "进行系统屏幕解锁": "perform system screen unlock",
    "打开系统选择文件": "Open System File Selector",
    "操作系统": "Operating System",
    "系统屏幕锁屏": "System Screen Lock",
    "关系": "Relationship",
    "岗位评分体系": "Position Scoring System",
    "系统会自动添": "system will auto add",
    "系统自动选择": "System Auto Select",
    "系统建议打开": "system suggests opening",
    "系统屏幕解锁": "System Screen Unlock",
    "元组": "Tuple",
    "数组": "Array",
    "按键组合": "Key Combination",
    "设置按键组合": "Set Key Combination",
    "编组开始": "Group Start",
    "编组结束": "Group End",
    "选择组件": "Select Component",
    "运行组件": "Run Component",
    "组件": "Component",
    "二维数组": "2D Array",
    "键盘符号组合": "Keyboard Symbol Combination",
    "混淆矩阵": "confusion matrix",
    
    # ============ REMAINING PHRASES BATCH 5 ============
    "选择组件": "select component",
    "运行组件": "run component",
    "纸尺寸": "paper size",
    "商规范": "business specification",
    "所选": "selected",
    "命名": "naming",
    "保留": "retain",
    "自增": "auto increment",
    "子级": "child level",
    "截取": "intercept",
    "直聘": "Zhipin",
    "场景": "scenario",
    "问答": "Q&A",
    "发生": "occur",
    "特殊": "special",
    "相似": "similar",
    "距离": "distance",
    "超过": "exceed",
    "展示": "display",
    "应文": "application text",
    "组件": "component",
    
    # Single character translations for remaining
    "剔": "remove",
    "差": "difference",
    "法": "method",
    "找": "find",
    "换": "change",
    "实": "real",
    "瞬": "instant",
    "只": "only",
    "彻": "completely",
    "通": "through",
    "信": "message",
    "延": "delay",
    "机": "machine",
    "母": "parent",
    "建": "create",
    "角": "corner",
    "侧": "side",
    "价": "price",
    "总": "total",
    "两": "two",
    "速": "speed",
    "纸": "paper",
    "按": "press",
    "留": "keep",
    "网": "web",
    "成": "into",
    "跨": "cross",
    "方": "direction",
    "写": "write",
    "完": "finish",
    "没": "no",
    "屏": "screen",
    "向": "toward",
    "经": "through",
    "相": "mutual",
    "白": "white",
    "填": "fill",
    "翻": "flip",
    "置": "place",
    "须": "must",
    "最": "most",
    "还": "also",
    "带": "with",
    "重": "re",
    "别": "other",
    "转": "turn",
    "序": "sequence",
    "智": "intelligent",
    "号": "number",
    "编": "code",
    "适": "fit",
    "增": "add",
    "安": "install",
    "段": "section",
    "含": "contain",
    "联": "link",
    "区": "region",
    "话": "speech",
    "追": "trace",
    "给": "give",
    "子": "child",
    "变": "variable",
    "应": "should",
    "独": "alone",
    "割": "cut",
    "微": "micro",
    "整": "whole",
    "其": "its",
    "图": "image",
    "体": "body",
    "维": "dimension",
    "清": "clear",
    "顿": "pause",
    "靠": "near",
    "标": "mark",
    "代": "generation",
    
    # ============ FINAL SINGLE CHARACTERS ============
    "尺寸": "size",
    "份": "copy",
    "阈": "threshold",
    "流": "flow",
    "击": "click",
    "第": "the",
    "示": "show",
    "存": "save",
    "用": "use",
    "赋": "assign",
    "盘": "disk",
    "一": "one",
    "日": "day",
    "内": "within",
    "粗": "bold",
    "起": "start",
    "捷": "shortcut",
    "过": "through",
    "码": "code",
    "所": "all",
    "数": "number",
    "力": "force",
    "包": "package",
    "人": "person",
    "痕": "trace",
    "面": "face",
    "移": "move",
    "位": "position",
    "仅": "only",
    "状": "state",
    "依": "depend",
    "视": "view",
    "作": "work",
    "部": "part",
    "此": "this",
    "称": "name",
    "选": "select",
    "去": "remove",
    "散": "scatter",
    "户": "user",
    "符": "symbol",
    "外": "outside",
    "自": "self",
    "初": "initial",
    "推": "push",
}

def translate_text(text):
    """Translate text using phrase translations first, then word translations"""
    result = text
    
    # Apply phrase translations first (longer phrases take priority)
    for cn, en in sorted(TRANSLATIONS.items(), key=lambda x: -len(x[0])):
        result = result.replace(cn, en)
    
    # Apply word translations for remaining Chinese
    for cn, en in sorted(WORD_TRANSLATIONS.items(), key=lambda x: -len(x[0])):
        result = result.replace(cn, en)
    
    return result

def main():
    input_file = r'e:\astron-rpa\astron-rpa-original\docker\volumes\mysql\init_c_atom_meta_data.sql'
    output_file = r'e:\astron-rpa\docker\volumes\mysql\init_c_atom_meta_data.sql'
    
    print(f"Reading from: {input_file}")
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    print(f"Original size: {len(content)} bytes")
    
    # Translate
    translated = translate_text(content)
    
    print(f"Translated size: {len(translated)} bytes")
    
    # Save
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(translated)
    
    print(f"Saved to: {output_file}")
    
    # Count remaining Chinese
    chinese_regex = re.compile(r'[\u4e00-\u9fff]+')
    remaining = chinese_regex.findall(translated)
    unique_remaining = set(remaining)
    
    print(f"\nRemaining Chinese phrases: {len(unique_remaining)}")
    if unique_remaining:
        print("Sample of remaining phrases:")
        for phrase in list(unique_remaining)[:30]:
            print(f"  - {phrase}")

if __name__ == '__main__':
    main()
