# -*- coding: utf-8 -*-
"""
Comprehensive translation script for all atom definitions in c_atom_meta table.
This translates Chinese UI text to English for the Astron RPA workflow builder.
"""

import json
import re
import sys

# Comprehensive Chinese to English translations
TRANSLATIONS = {
    # ===========================================
    # ATOM TITLES (shown in tree and headers)
    # ===========================================
    
    # AI
    "大模型": "Large Language Models",
    "多轮会话": "Multi-turn Conversation",
    "单轮会话": "Single-turn Conversation", 
    "知识问答": "Knowledge Q&A",
    "主题扩写": "Topic Expansion",
    "段落扩写": "Paragraph Expansion",
    "段落缩写": "Paragraph Abbreviation",
    "简历评分": "Resume Scoring",
    "职位关键词生成": "Job Keyword Generation",
    "合同要素提取": "Contract Element Extraction",
    "调用Dify工作流": "Call Dify Workflow",
    "调用Dify对话流": "Call Dify Chatflow",
    "调用星辰Agent流程": "Call XingChen Agent Flow",
    
    # OCR
    "营业执照识别": "Business License Recognition",
    "身份证识别": "ID Card Recognition",
    "增值税发票识别": "VAT Invoice Recognition",
    "火车票识别": "Train Ticket Recognition",
    "出租车发票识别": "Taxi Invoice Recognition",
    "通用文字识别": "General Text Recognition",
    
    # Verification
    "验证码": "Verification Code",
    "通用数英验证码": "General Alphanumeric Captcha",
    "通用滑块验证码": "General Slider Captcha",
    "通用点击验证码": "General Click Captcha",
    
    # Process
    "流程": "Process",
    "运行子流程": "Run Sub-process",
    "运行Python模块": "Run Python Module",
    
    # Code Flow
    "代码流程": "Code Flow",
    "设置变量值": "Set Variable Value",
    "日志打印": "Log Print",
    "条件判断": "Conditional",
    "IF条件": "IF Condition",
    "IF图像存在": "IF Image Exists",
    "IF文件夹存在": "IF Folder Exists",
    "IF文件存在": "IF File Exists",
    "IF窗口存在": "IF Window Exists",
    "ELSE IF条件": "ELSE IF Condition",
    "ELSE条件": "ELSE Condition",
    "循环": "Loop",
    "字典For循环": "Dictionary For Loop",
    "列表For循环": "List For Loop",
    "计数For循环": "Count For Loop",
    "循环Excel内容": "Loop Excel Content",
    "循环相似元素列表（web）": "Loop Similar Elements (Web)",
    "While循环": "While Loop",
    "退出循环（Break）": "Exit Loop (Break)",
    "继续下次循环（Continue）": "Continue Next Loop (Continue)",
    "错误处理": "Error Handling",
    "捕获异常（Try)": "Catch Exception (Try)",
    "捕获异常（Finally)": "Catch Exception (Finally)",
    
    # Web Automation
    "网页自动化": "Web Automation",
    "网页操作": "Page Operations",
    "打开浏览器": "Open Browser",
    "关闭浏览器": "Close Browser",
    "获取已打开的浏览器对象": "Get Opened Browser Objects",
    "元素是否存在（web）": "Element Exists (Web)",
    "等待元素（web）": "Wait for Element (Web)",
    "元素操作（web）": "Element Operations (Web)",
    "点击元素（web）": "Click Element (Web)",
    "获取元素文本内容（web）": "Get Element Text (Web)",
    "填写输入框（web）": "Fill Input Box (Web)",
    "获取复选框（web）": "Get Checkbox (Web)",
    "操作复选框（web）": "Operate Checkbox (Web)",
    "获取下拉框（web）": "Get Dropdown (Web)",
    "操作下拉框（web）": "Operate Dropdown (Web)",
    "拾取滑块拖拽（web）": "Pick Slider Drag (Web)",
    "鼠标悬停在元素上（web）": "Mouse Hover Element (Web)",
    "拾取元素截图（web）": "Pick Element Screenshot (Web)",
    "元素位置截图（web）": "Element Position Screenshot (Web)",
    "元素置于可视区域（web）": "Scroll Element to View (Web)",
    "获取表格数据（web）": "Get Table Data (Web)",
    "数据抓取（web）": "Data Scraping (Web)",
    "获取相似元素列表（web）": "Get Similar Elements (Web)",
    "获取元素对象（web）": "Get Element Object (Web)",
    "获取关联元素（web）": "Get Related Elements (Web)",
    "网页文件": "Web File",
    "设置Cookie": "Set Cookie",
    "获取Cookie": "Get Cookie",
    "打开新网页": "Open New Page",
    "获取当前标签页ID": "Get Current Tab ID",
    "切换到已存在标签页": "Switch to Existing Tab",
    "关闭网页": "Close Page",
    "刷新当前网页": "Refresh Current Page",
    "停止加载网页": "Stop Loading Page",
    "网页前进": "Page Forward",
    "网页后退": "Page Backward",
    "网页截图": "Page Screenshot",
    "鼠标滚动网页": "Mouse Scroll Page",
    "获取网页URL": "Get Page URL",
    "获取网页标题": "Get Page Title",
    "等待页面加载完成": "Wait for Page Load",
    "文件下载（web）": "File Download (Web)",
    "文件上传（web）": "File Upload (Web)",
    
    # Desktop Automation
    "桌面自动化": "Desktop Automation",
    "窗口操作": "Window Operations",
    "关闭程序": "Close Program",
    "打开程序": "Open Program",
    "点击元素（桌面）": "Click Element (Desktop)",
    "元素截图（桌面）": "Element Screenshot (Desktop)",
    "鼠标悬停元素（桌面）": "Mouse Hover Element (Desktop)",
    "填写输入框（桌面）": "Fill Input Box (Desktop)",
    "获取元素文本（桌面）": "Get Element Text (Desktop)",
    "获取相似元素列表（桌面）": "Get Similar Elements (Desktop)",
    "置顶窗口": "Pin Window to Top",
    "关闭窗口": "Close Window",
    "调整窗口大小": "Resize Window",
    
    # Document Processing
    "文档处理": "Document Processing",
    
    # PDF
    "获取PDF文档页数": "Get PDF Page Count",
    "提取PDF文档文本": "Extract PDF Text",
    "合并PDF文件": "Merge PDF Files",
    "提取PDF文档图片": "Extract PDF Images",
    "抽取PDF指定页": "Extract PDF Pages",
    "提取PDF表格到Excel": "Extract PDF Table to Excel",
    "PDF页面转图片": "PDF Page to Image",
    
    # Word
    "打开Word": "Open Word",
    "读取Word内容": "Read Word Content",
    "创建Word": "Create Word",
    "保存Word": "Save Word",
    "关闭Word": "Close Word",
    "插入文本到Word": "Insert Text to Word",
    "选择Word文本": "Select Word Text",
    "定位Word光标": "Position Word Cursor",
    "移动Word光标": "Move Word Cursor",
    "Word插入页/段落": "Word Insert Page/Paragraph",
    "Word插入超链接": "Word Insert Hyperlink",
    "Word插入图片": "Word Insert Image",
    "Word读取表格": "Word Read Table",
    "Word插入表格": "Word Insert Table",
    "Word删除内容": "Word Delete Content",
    "Word替换内容": "Word Replace Content",
    "Word创建批注": "Word Create Comment",
    "Word删除批注": "Word Delete Comment",
    "Word导出为PDF/TXT": "Word Export to PDF/TXT",
    
    # Excel
    "打开Excel": "Open Excel",
    "添加Excel工作表": "Add Excel Worksheet",
    "获取已打开的Excel对象": "Get Opened Excel Objects",
    "创建Excel": "Create Excel",
    "保存Excel": "Save Excel",
    "关闭Excel": "Close Excel",
    "写入Excel": "Write to Excel",
    "读取Excel内容": "Read Excel Content",
    "设置单元格格式": "Set Cell Format",
    "复制Excel单元格": "Copy Excel Cell",
    "粘贴Excel单元格": "Paste Excel Cell",
    "删除Excel单元格": "Delete Excel Cell",
    "获取Excel工作表名称": "Get Excel Sheet Names",
    "清除Excel区域内容": "Clear Excel Range",
    "插入Excel行或列": "Insert Excel Row/Column",
    "获取Excel行数": "Get Excel Row Count",
    "获取Excel列数": "Get Excel Column Count",
    "获取Excel第一个可用行": "Get Excel First Available Row",
    "获取Excel第一个可用列": "Get Excel First Available Column",
    "设置Excel行高": "Set Excel Row Height",
    "设置Excel列宽": "Set Excel Column Width",
    "获取Excel单元格颜色": "Get Excel Cell Color",
    "合并或拆分Excel单元格": "Merge/Split Excel Cells",
    "移动Excel工作表": "Move Excel Worksheet",
    "删除Excel工作表": "Delete Excel Worksheet",
    "重命名Excel工作表": "Rename Excel Worksheet",
    "复制Excel工作表": "Copy Excel Worksheet",
    "查找或替换Excel内容": "Find/Replace Excel Content",
    "插入Excel图片": "Insert Excel Image",
    "插入Excel公式": "Insert Excel Formula",
    "创建Excel批注": "Create Excel Comment",
    "删除Excel批注": "Delete Excel Comment",
    "Excel区域文本转数字": "Excel Text to Number",
    "Excel区域数字转文本": "Excel Number to Text",
    
    # Mouse & Keyboard
    "鼠标键盘": "Mouse & Keyboard",
    "键盘输入": "Keyboard Input",
    "鼠标点击": "Mouse Click",
    "鼠标滚动": "Mouse Scroll",
    "鼠标移动": "Mouse Move",
    "鼠标拖拽": "Mouse Drag",
    "获取鼠标位置": "Get Mouse Position",
    "键盘模拟按键": "Keyboard Simulate Key",
    
    # Data Processing
    "数据处理": "Data Processing",
    "数学操作": "Math Operations",
    "字符串操作": "String Operations",
    "列表操作": "List Operations",
    "字典操作": "Dictionary Operations",
    "时间操作": "Time Operations",
    
    # Math
    "生成随机数": "Generate Random Number",
    "四舍五入": "Round Number",
    "自增自减": "Increment/Decrement",
    "获取绝对值": "Get Absolute Value",
    "数学计算": "Math Calculation",
    
    # String
    "文本提取内容": "Extract Text Content",
    "文本替换内容": "Replace Text Content",
    "列表聚合为文本": "List to Text",
    "文本分割为列表": "Text to List",
    "文本合并": "Merge Text",
    "文本补齐至固定长度": "Pad Text to Length",
    "文本去除两侧空格": "Trim Text Spaces",
    "截取固定长度文本": "Substring Fixed Length",
    "更改文本大小写": "Change Text Case",
    "获取文本长度": "Get Text Length",
    "JSON字符串互转": "JSON String Convert",
    "其他格式转文本": "Other Format to Text",
    "文本转其他格式": "Text to Other Format",
    
    # List
    "创建新列表": "Create New List",
    "清空列表": "Clear List",
    "列表插入值": "List Insert Value",
    "列表修改值": "List Modify Value",
    "获取值在列表位置": "Get Value Position in List",
    "列表删除值": "List Remove Value",
    "列表排序": "List Sort",
    "列表随机打乱顺序": "List Shuffle",
    "剔除列表中的多项": "Remove Multiple from List",
    "列表反转": "List Reverse",
    "列表合并": "List Merge",
    "列表去重": "List Remove Duplicates",
    "获取两个列表的重复项": "Get List Duplicates",
    "根据索引获取列表值": "Get List Value by Index",
    "获取列表长度": "Get List Length",
    
    # Dictionary
    "创建新字典": "Create New Dictionary",
    "字典设置值": "Dictionary Set Value",
    "字典删除值": "Dictionary Delete Value",
    "字典获取值": "Dictionary Get Value",
    "获取字典所有键": "Get Dictionary All Keys",
    "获取字典所有值": "Get Dictionary All Values",
    
    # Time
    "获取当前时间": "Get Current Time",
    "设置时间": "Set Time",
    "时间对象转时间戳": "DateTime to Timestamp",
    "时间戳转时间对象": "Timestamp to DateTime",
    "获取时间差": "Get Time Difference",
    "输出指定格式时间文本": "Output Formatted Time",
    
    # Operating System
    "操作系统": "Operating System",
    "文件操作": "File Operations",
    "文件夹操作": "Folder Operations",
    "压缩/解压": "Compress/Decompress",
    "系统命令": "System Commands",
    "截图": "Screenshot",
    "剪切板": "Clipboard",
    
    # File Operations
    "创建文件": "Create File",
    "写入文件": "Write File",
    "读取文件": "Read File",
    "复制文件": "Copy File",
    "移动文件": "Move File",
    "重命名文件": "Rename File",
    "删除文件": "Delete File",
    "查找文件": "Find File",
    "等待文件": "Wait for File",
    "获取文件编码类型": "Get File Encoding",
    "获取文件信息": "Get File Info",
    "获取文件列表": "Get File List",
    "上传文件至共享文件夹": "Upload to Shared Folder",
    "从共享文件夹下载文件": "Download from Shared Folder",
    
    # Folder Operations
    "创建文件夹": "Create Folder",
    "打开文件夹": "Open Folder",
    "复制文件夹": "Copy Folder",
    "移动文件夹": "Move Folder",
    "重命名文件夹": "Rename Folder",
    "清空文件夹": "Clear Folder",
    "删除文件夹": "Delete Folder",
    "获取文件夹列表": "Get Folder List",
    
    # Compress
    "压缩": "Compress",
    "解压": "Decompress",
    
    # System
    "运行或打开": "Run or Open",
    "获取进程PID": "Get Process PID",
    "终止进程": "Terminate Process",
    "屏幕截图": "Screen Screenshot",
    "复制到剪切板": "Copy to Clipboard",
    "清空剪切板": "Clear Clipboard",
    "获取剪切板": "Get Clipboard",
    
    # Encryption
    "加解密/编解码": "Encryption/Encoding",
    "SHA加密": "SHA Encryption",
    "MD5加密": "MD5 Encryption",
    "对称解密": "Symmetric Decryption",
    "对称加密": "Symmetric Encryption",
    "Base64解码": "Base64 Decode",
    "Base64编码": "Base64 Encode",
    
    # Network
    "网络": "Network",
    "邮件": "Email",
    "发送邮件": "Send Email",
    "接收邮件": "Receive Email",
    "HTTP请求": "HTTP Request",
    "HTTP下载": "HTTP Download",
    "创建FTP连接": "Create FTP Connection",
    "关闭FTP连接": "Close FTP Connection",
    "获取工作目录(FTP)": "Get Work Directory (FTP)",
    "切换工作目录(FTP)": "Change Work Directory (FTP)",
    "创建文件夹(FTP)": "Create Folder (FTP)",
    "获取文件/文件夹(FTP)": "Get File/Folder (FTP)",
    "上传文件/文件夹(FTP)": "Upload File/Folder (FTP)",
    "重命名文件/文件夹(FTP)": "Rename File/Folder (FTP)",
    "下载文件/文件夹(FTP)": "Download File/Folder (FTP)",
    "删除文件/文件夹(FTP)": "Delete File/Folder (FTP)",
    
    # CV Image
    "CV图像": "CV Image",
    "点击图像": "Click Image",
    "鼠标悬浮在图像上": "Mouse Hover on Image",
    "等待图像": "Wait for Image",
    "图像输入框输入": "Image Input Box Input",
    
    # Dialog
    "对话框": "Dialog",
    "消息提示框": "Message Dialog",
    "输入对话框": "Input Dialog",
    "选择对话框": "Select Dialog",
    "日期时间选择框": "DateTime Picker",
    "文件选择对话框": "File Select Dialog",
    "自定义对话框": "Custom Dialog",
    
    # Script
    "自定义脚本": "Custom Script",
    "JS脚本": "JS Script",
    
    # Remote/Center
    "卓越中心": "Excellence Center",
    "获取共享变量": "Get Shared Variable",
    
    # Feishu
    "飞书": "Feishu",
    "连接到多维表格": "Connect to Multi-sheet",
    "列出记录（筛选）": "List Records (Filtered)",
    "列出记录（指定）": "List Records (Specified)",
    "创建记录": "Create Record",
    "更新记录": "Update Record",
    "删除记录": "Delete Record",
    "列出数据表": "List Data Tables",
    "新增数据表": "Add Data Table",
    "删除数据表": "Delete Data Table",
    "重命名数据表": "Rename Data Table",
    "列出字段": "List Fields",
    "新增字段": "Add Field",
    "更新字段": "Update Field",
    "删除字段": "Delete Field",
    "连接数据表": "Connect to Table",
    "获取工作表信息": "Get Worksheet Info",
    "设置筛选器": "Set Filter",
    "获取筛选结果": "Get Filter Result",
    "读取工作表数据": "Read Worksheet Data",
    "写入数据": "Write Data",
    
    # ===========================================
    # INPUT FIELD LABELS (shown in right panel)
    # ===========================================
    
    "任务名称": "Task Name",
    "任务别名": "Task Alias",
    "浏览器对象": "Browser Object",
    "悬停元素拾取": "Hover Element Pick",
    "拾取元素": "Pick Element",
    "等待元素出现时间（秒）": "Wait for Element Timeout (sec)",
    "等待元素出现时间": "Wait for Element Timeout",
    "选择要等待页面所在的浏览器对象": "Select browser object for the page to wait",
    "拾取鼠标要悬停的元素": "Pick the element for mouse to hover",
    "超过该时间停止等待": "Stop waiting after this time",
    
    # Common input field labels
    "网址": "URL",
    "地址": "Address",
    "文件路径": "File Path",
    "文件夹路径": "Folder Path",
    "保存路径": "Save Path",
    "输出路径": "Output Path",
    "输入路径": "Input Path",
    "目标路径": "Target Path",
    "源路径": "Source Path",
    "新名称": "New Name",
    "新路径": "New Path",
    "文件名": "File Name",
    "文件夹名": "Folder Name",
    "工作表名": "Sheet Name",
    "工作表名称": "Sheet Name",
    "单元格": "Cell",
    "单元格区域": "Cell Range",
    "起始单元格": "Start Cell",
    "结束单元格": "End Cell",
    "行号": "Row Number",
    "列号": "Column Number",
    "行数": "Row Count",
    "列数": "Column Count",
    "起始行": "Start Row",
    "起始列": "Start Column",
    "结束行": "End Row",
    "结束列": "End Column",
    "内容": "Content",
    "文本": "Text",
    "文本内容": "Text Content",
    "输入内容": "Input Content",
    "输入文本": "Input Text",
    "输出内容": "Output Content",
    "输出文本": "Output Text",
    "变量名": "Variable Name",
    "变量值": "Variable Value",
    "变量": "Variable",
    "参数": "Parameter",
    "参数名": "Parameter Name",
    "参数值": "Parameter Value",
    "选项": "Option",
    "选择": "Select",
    "类型": "Type",
    "格式": "Format",
    "编码": "Encoding",
    "密码": "Password",
    "用户名": "Username",
    "账号": "Account",
    "主机": "Host",
    "端口": "Port",
    "超时": "Timeout",
    "超时时间": "Timeout Duration",
    "超时时间（秒）": "Timeout (sec)",
    "延迟": "Delay",
    "延迟时间": "Delay Time",
    "延迟时间（秒）": "Delay (sec)",
    "等待时间": "Wait Time",
    "等待时间（秒）": "Wait Time (sec)",
    "间隔": "Interval",
    "间隔时间": "Interval Time",
    "重试次数": "Retry Count",
    "重试次数(次)": "Retry Count",
    "重试间隔": "Retry Interval",
    "重试间隔(秒)": "Retry Interval (sec)",
    "最大次数": "Max Count",
    "最大数量": "Max Quantity",
    "最小值": "Min Value",
    "最大值": "Max Value",
    "默认值": "Default Value",
    "初始值": "Initial Value",
    "步长": "Step",
    "精度": "Precision",
    "小数位数": "Decimal Places",
    "宽度": "Width",
    "高度": "Height",
    "大小": "Size",
    "位置": "Position",
    "坐标": "Coordinates",
    "X坐标": "X Coordinate",
    "Y坐标": "Y Coordinate",
    "左": "Left",
    "右": "Right",
    "上": "Top",
    "下": "Bottom",
    "方向": "Direction",
    "模式": "Mode",
    "状态": "Status",
    "结果": "Result",
    "输出": "Output",
    "输入": "Input",
    "返回值": "Return Value",
    "返回结果": "Return Result",
    
    # Element operations
    "元素": "Element",
    "元素对象": "Element Object",
    "元素数据": "Element Data",
    "元素列表": "Element List",
    "元素索引": "Element Index",
    "元素文本": "Element Text",
    "元素属性": "Element Attribute",
    "元素值": "Element Value",
    "目标元素": "Target Element",
    "父元素": "Parent Element",
    "子元素": "Child Element",
    "相邻元素": "Adjacent Element",
    "相似元素": "Similar Elements",
    "网页元素": "Web Element",
    "桌面元素": "Desktop Element",
    "图像元素": "Image Element",
    "拾取": "Pick",
    "拾取元素数据": "Pick Element Data",
    "点击元素数据": "Click Element Data",
    "输入框元素数据": "Input Box Element Data",
    "点击方式": "Click Method",
    "点击类型": "Click Type",
    "鼠标按钮": "Mouse Button",
    "点击次数": "Click Count",
    "双击": "Double Click",
    "单击": "Single Click",
    "右键点击": "Right Click",
    "左键": "Left Button",
    "右键": "Right Button",
    "中键": "Middle Button",
    "滚动距离": "Scroll Distance",
    "滚动方向": "Scroll Direction",
    "向上": "Up",
    "向下": "Down",
    "向左": "To Left",
    "向右": "To Right",
    
    # Browser operations
    "浏览器": "Browser",
    "浏览器类型": "Browser Type",
    "页面": "Page",
    "标签页": "Tab",
    "标签页ID": "Tab ID",
    "Cookie名称": "Cookie Name",
    "Cookie值": "Cookie Value",
    "Cookie域": "Cookie Domain",
    "Cookie路径": "Cookie Path",
    "下载文件名": "Download Filename",
    "下载路径": "Download Path",
    "上传文件": "Upload File",
    "上传文件路径": "Upload File Path",
    "是否等待下载完成": "Wait for Download Complete",
    "是否等待加载完成": "Wait for Page Load",
    "是否新标签页打开": "Open in New Tab",
    "是否无头模式": "Headless Mode",
    "是否最大化": "Maximize",
    "是否隐藏浏览器": "Hide Browser",
    
    # Window operations
    "窗口": "Window",
    "窗口标题": "Window Title",
    "窗口句柄": "Window Handle",
    "窗口类名": "Window Class Name",
    "程序": "Program",
    "程序路径": "Program Path",
    "程序名称": "Program Name",
    "进程": "Process",
    "进程ID": "Process ID",
    "进程名": "Process Name",
    
    # Excel operations
    "Excel对象": "Excel Object",
    "Excel文件": "Excel File",
    "Excel文件路径": "Excel File Path",
    "工作簿": "Workbook",
    "工作表": "Worksheet",
    "工作表索引": "Sheet Index",
    "单元格值": "Cell Value",
    "单元格格式": "Cell Format",
    "单元格颜色": "Cell Color",
    "背景颜色": "Background Color",
    "字体颜色": "Font Color",
    "字体大小": "Font Size",
    "字体名称": "Font Name",
    "是否加粗": "Bold",
    "是否斜体": "Italic",
    "是否有表头": "Has Header",
    "是否覆盖": "Overwrite",
    "是否追加": "Append",
    "公式": "Formula",
    "批注": "Comment",
    "批注内容": "Comment Content",
    
    # Word operations
    "Word对象": "Word Object",
    "Word文件": "Word File",
    "Word文件路径": "Word File Path",
    "段落": "Paragraph",
    "段落索引": "Paragraph Index",
    "页码": "Page Number",
    "书签": "Bookmark",
    "书签名称": "Bookmark Name",
    "超链接": "Hyperlink",
    "超链接地址": "Hyperlink URL",
    "图片": "Image",
    "图片路径": "Image Path",
    "表格": "Table",
    "表格索引": "Table Index",
    "表格行": "Table Row",
    "表格列": "Table Column",
    
    # PDF operations
    "PDF文件": "PDF File",
    "PDF文件路径": "PDF File Path",
    "页面范围": "Page Range",
    "起始页": "Start Page",
    "结束页": "End Page",
    "页数": "Page Count",
    
    # Time operations
    "时间": "Time",
    "日期": "Date",
    "日期时间": "DateTime",
    "时间戳": "Timestamp",
    "时间格式": "Time Format",
    "日期格式": "Date Format",
    "年": "Year",
    "月": "Month",
    "日": "Day",
    "时": "Hour",
    "分": "Minute",
    "秒": "Second",
    "毫秒": "Millisecond",
    "周": "Week",
    "周几": "Weekday",
    
    # List operations
    "列表": "List",
    "列表值": "List Value",
    "列表索引": "List Index",
    "列表长度": "List Length",
    "列表项": "List Item",
    "起始索引": "Start Index",
    "结束索引": "End Index",
    "插入位置": "Insert Position",
    "排序方式": "Sort Method",
    "升序": "Ascending",
    "降序": "Descending",
    
    # Dictionary operations
    "字典": "Dictionary",
    "字典值": "Dictionary Value",
    "字典键": "Dictionary Key",
    "键": "Key",
    "值": "Value",
    "键值对": "Key-Value Pair",
    
    # String operations
    "字符串": "String",
    "文本值": "Text Value",
    "查找文本": "Find Text",
    "替换文本": "Replace Text",
    "分隔符": "Separator",
    "连接符": "Connector",
    "前缀": "Prefix",
    "后缀": "Suffix",
    "填充字符": "Padding Character",
    "填充长度": "Padding Length",
    "截取长度": "Substring Length",
    "截取起始": "Substring Start",
    "大写": "Uppercase",
    "小写": "Lowercase",
    "首字母大写": "Title Case",
    "正则表达式": "Regular Expression",
    "匹配模式": "Match Pattern",
    "提取模式": "Extract Pattern",
    "替换模式": "Replace Pattern",
    
    # Math operations
    "数值": "Number",
    "整数": "Integer",
    "浮点数": "Float",
    "随机数": "Random Number",
    "最小随机数": "Min Random",
    "最大随机数": "Max Random",
    "运算符": "Operator",
    "加": "Add",
    "减": "Subtract",
    "乘": "Multiply",
    "除": "Divide",
    "取余": "Modulo",
    "幂": "Power",
    "绝对值": "Absolute Value",
    "四舍五入位数": "Round Digits",
    
    # Encryption operations
    "加密": "Encrypt",
    "解密": "Decrypt",
    "编码": "Encode",
    "解码": "Decode",
    "密钥": "Key",
    "加密算法": "Encryption Algorithm",
    "哈希值": "Hash Value",
    
    # Network operations
    "请求地址": "Request URL",
    "请求方式": "Request Method",
    "请求头": "Request Headers",
    "请求体": "Request Body",
    "请求参数": "Request Parameters",
    "响应": "Response",
    "响应状态码": "Response Status Code",
    "响应头": "Response Headers",
    "响应体": "Response Body",
    "FTP连接": "FTP Connection",
    "FTP对象": "FTP Object",
    "远程路径": "Remote Path",
    "本地路径": "Local Path",
    
    # Email operations
    "邮件服务器": "Email Server",
    "发件人": "Sender",
    "收件人": "Recipient",
    "抄送": "CC",
    "密送": "BCC",
    "邮件主题": "Email Subject",
    "邮件正文": "Email Body",
    "邮件附件": "Email Attachment",
    "附件路径": "Attachment Path",
    "是否HTML格式": "Is HTML Format",
    
    # Dialog operations
    "对话框标题": "Dialog Title",
    "提示信息": "Prompt Message",
    "提示内容": "Prompt Content",
    "按钮文本": "Button Text",
    "确定": "OK",
    "取消": "Cancel",
    "是": "Yes",
    "否": "No",
    "选项列表": "Option List",
    "默认选项": "Default Option",
    "输入类型": "Input Type",
    "输入提示": "Input Hint",
    "文件类型": "File Type",
    "文件过滤": "File Filter",
    "允许多选": "Allow Multiple",
    
    # Image operations  
    "图像": "Image",
    "图像路径": "Image Path",
    "截图区域": "Screenshot Area",
    "截图路径": "Screenshot Path",
    "相似度": "Similarity",
    "匹配度": "Match Score",
    "查找图像": "Find Image",
    "目标图像": "Target Image",
    "模板图像": "Template Image",
    
    # Condition operations
    "条件": "Condition",
    "条件表达式": "Condition Expression",
    "判断条件": "Judgment Condition",
    "循环条件": "Loop Condition",
    "循环变量": "Loop Variable",
    "循环次数": "Loop Count",
    "起始值": "Start Value",
    "结束值": "End Value",
    "异常处理": "Exception Handling",
    "异常类型": "Exception Type",
    "异常信息": "Exception Message",
    
    # Process operations
    "子流程": "Sub-process",
    "子流程路径": "Sub-process Path",
    "子流程参数": "Sub-process Parameters",
    "Python模块": "Python Module",
    "Python模块路径": "Python Module Path",
    "脚本内容": "Script Content",
    "脚本路径": "Script Path",
    
    # AI operations
    "模型": "Model",
    "模型名称": "Model Name",
    "提示词": "Prompt",
    "系统提示词": "System Prompt",
    "用户提示词": "User Prompt",
    "历史对话": "Chat History",
    "最大令牌数": "Max Tokens",
    "温度": "Temperature",
    "知识库": "Knowledge Base",
    "知识库ID": "Knowledge Base ID",
    
    # Remote/Shared
    "共享变量": "Shared Variable",
    "共享变量名": "Shared Variable Name",
    "共享变量值": "Shared Variable Value",
    
    # Feishu specific
    "飞书对象": "Feishu Object",
    "多维表格": "Multi-sheet",
    "多维表格ID": "Multi-sheet ID",
    "数据表": "Data Table",
    "数据表ID": "Table ID",
    "记录ID": "Record ID",
    "字段": "Field",
    "字段ID": "Field ID",
    "字段名": "Field Name",
    "字段类型": "Field Type",
    "字段值": "Field Value",
    "筛选条件": "Filter Condition",
    
    # ===========================================
    # COMMENTS/DESCRIPTIONS (shown in workflow)
    # ===========================================
    
    "鼠标悬停在浏览器对象": "Mouse hover on browser object",
    "中的元素": "'s element",
    "上": " on",
    "打开": "Open",
    "关闭": "Close",
    "获取": "Get",
    "设置": "Set",
    "创建": "Create",
    "删除": "Delete",
    "复制": "Copy",
    "粘贴": "Paste",
    "移动": "Move",
    "重命名": "Rename",
    "保存": "Save",
    "读取": "Read",
    "写入": "Write",
    "执行": "Execute",
    "运行": "Run",
    "停止": "Stop",
    "等待": "Wait",
    "查找": "Find",
    "替换": "Replace",
    "提取": "Extract",
    "插入": "Insert",
    "合并": "Merge",
    "拆分": "Split",
    "排序": "Sort",
    "过滤": "Filter",
    "转换": "Convert",
    "验证": "Verify",
    "检查": "Check",
    "判断": "Judge",
    "循环": "Loop",
    "遍历": "Iterate",
    "跳过": "Skip",
    "继续": "Continue",
    "退出": "Exit",
    "返回": "Return",
    "调用": "Call",
    "发送": "Send",
    "接收": "Receive",
    "上传": "Upload",
    "下载": "Download",
    "连接": "Connect",
    "断开": "Disconnect",
    "登录": "Login",
    "登出": "Logout",
    "刷新": "Refresh",
    "截图": "Screenshot",
    "点击": "Click",
    "输入": "Input",
    "选择": "Select",
    "勾选": "Check",
    "取消勾选": "Uncheck",
    "拖拽": "Drag",
    "滚动": "Scroll",
    "悬停": "Hover",
    "聚焦": "Focus",
    "模拟": "Simulate",
    "触发": "Trigger",
    
    # Comment templates
    "将结果输出为浏览器对象": "Output result as browser object",
    "将执行结果输出平": "Output execution result to",
    "执行行结果输出为": "Output execution result as",
    "将执行结果输出为": "Output execution result as",
    "执行结果输出为": "Output result as",
    "打开浏览器并进入初始网址": "Open browser and navigate to initial URL",
    "关闭浏览器对象": "Close browser object",
    "在浏览器对象": "In browser object",
    "中获取复选框": "get checkbox",
    "中操作复选框": "operate checkbox",
    "后": "then",
    "中拾取元素": "pick element",
    "中获取输入框": "get input box",
    "中获取下拉框": "get dropdown",
    "中操作下拉框": "operate dropdown",
    "的形式输入内容": "input content in the form of",
    "将执行结果输出为": "output result as",
    "以": "with",
    "键盘输入": "keyboard input",
    
    # ===========================================
    # ADVANCED PARAMETERS
    # ===========================================
    
    "高级参数": "Advanced Parameters",
    "打印输出变量值": "Print Output Variable Value",
    "执行前延迟(秒)": "Delay Before Execution (sec)",
    "执行后延迟(秒)": "Delay After Execution (sec)",
    "执行异常时": "On Execution Error",
    "重试": "Retry",
    
    # ===========================================
    # DATA TYPES
    # ===========================================
    
    "任意值": "Any Value",
    "任何值": "Any Value",
    "布尔值": "Boolean",
    "对话框输出结果": "Dialog Output Result",
    "飞书对象": "Feishu Object",
    
    # ===========================================
    # FUNCTION DESCRIPTIONS
    # ===========================================
    
    "转文本": "To Text",
    "取整数部分": "Get Integer Part",
    "转整数": "To Integer",
    "转数值": "To Number",
    "删除两端空格": "Trim Spaces",
    "列表第": "List Item",
    "项": "Item",
    "列表倒数第": "List Item from End",
    "的值": "Value",
    "字典包含元素个数": "Dictionary Element Count",
    "根目录": "Root Directory",
    "父目录": "Parent Directory",
    "文件名称": "File Name",
    "文件名称(不带扩展名)": "File Name (No Extension)",
    "文件扩展名": "File Extension",
    "获取年份": "Get Year",
    "获取月份": "Get Month",
    "获取日": "Get Day",
    "获取小时": "Get Hour",
    "获取分钟": "Get Minute",
    "获取秒": "Get Second",
    "获取周几": "Get Weekday",
    "获取周数": "Get Week Number",
    "该网页的地址": "Page URL",
    "该网页的标题": "Page Title",
    "文件所在位置": "File Location",
    "第一个可用行": "First Available Row",
    
    # Template values - use curly quotes
    "\u201c你好\u201d": "\u201cHello\u201d",
    "小明": "John",
    "true或者false": "true or false",
    "到第": " to ",
    "对象": "Object",
    
    # More comment patterns
    "并进入初始网址": "and navigate to initial URL",
    "，将结果输出为浏览器对象": ", output result as browser object",
    "中打开Cookie设置页": "open Cookie settings page in",
    "中获取名为": "get named",
    "的Cookie数据": "Cookie data",
    "的Cookie数据，将结果输出为": "Cookie data, output result as",
    "为浏览器对象": "as browser object",
    "设置名为": "set named",
    "的Cookie": "Cookie",
    "在浏览器对象": "In browser object",
    "中新增一个标签页并打开网页": "add a new tab and open page",
    "获取浏览器对象": "Get browser object",
    "中当前激活的标签页ID，将执行结果输出为": "current active tab ID, output result as",
    "切换浏览器对象": "Switch browser object",
    "中的标签页为": "tab to",
    "关闭浏览器对象": "Close browser object",
    "中激活的网页": "activated page in",
    "刷新浏览器对象": "Refresh browser object",
    "中的当前标签页": "current tab in",
    "停止加载浏览器对象": "Stop loading browser object",
    "前进浏览器对象": "Forward browser object",
    "后退浏览器对象": "Back browser object",
    "网页截图，保存路径": "Page screenshot, save path",
    "，将执行结果输出为": ", output result as",
    "鼠标滚动浏览器对象": "Mouse scroll browser object",
    "中的网页": "page in",
    "中，滚动": "scroll",
    "像素": "pixels",
    "获取浏览器对象": "Get browser object",
    "中当前网页的URL，将执行结果输出为": "current page URL, output result as",
    "中当前网页的标题，将执行结果输出为": "current page title, output result as",
    "等待浏览器对象": "Wait for browser object",
    "中当前网页加载完成": "current page to finish loading",
    "在浏览器对象": "In browser object",
    "中拾取下载文件": "pick download file",
    "后保存至": "then save to",
    "中拾取上传元素": "pick upload element",
    "后上传文件": "then upload file",
    "等待元素": "Wait for element",
    "出现": "to appear",
    "元素操作": "Element operation",
    "点击元素": "Click element",
    "获取元素文本内容": "Get element text",
    "填写输入框": "Fill input box",
    "获取复选框": "Get checkbox",
    "操作复选框": "Operate checkbox",
    "获取下拉框": "Get dropdown",
    "操作下拉框": "Operate dropdown",
    "拾取滑块拖拽": "Pick slider drag",
    "鼠标悬停在元素上": "Mouse hover on element",
    "拾取元素截图": "Pick element screenshot",
    "元素位置截图": "Element position screenshot",
    "元素置于可视区域": "Scroll element into view",
    "获取表格数据": "Get table data",
    "数据抓取": "Data scraping",
    "获取相似元素列表": "Get similar elements",
    "获取元素对象": "Get element object",
    "获取关联元素": "Get related elements",
}

def translate_text(text):
    """Translate a single text string"""
    if text in TRANSLATIONS:
        return TRANSLATIONS[text]
    return text

def translate_in_string(s):
    """Replace all Chinese phrases in a string with English translations"""
    result = s
    # Sort by length descending to replace longer phrases first
    for cn, en in sorted(TRANSLATIONS.items(), key=lambda x: -len(x[0])):
        result = result.replace(cn, en)
    return result

def main():
    # Read the original SQL file with all atoms
    input_file = r'e:\astron-rpa\astron-rpa-original\docker\volumes\mysql\init_c_atom_meta_data.sql'
    output_file = r'e:\astron-rpa\docker\volumes\mysql\init_c_atom_meta_data.sql'
    
    print(f"Reading from: {input_file}")
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    print(f"Original size: {len(content)} bytes")
    
    # Translate the content
    translated = translate_in_string(content)
    
    print(f"Translated size: {len(translated)} bytes")
    
    # Save translated content
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(translated)
    
    print(f"Saved to: {output_file}")
    
    # Count remaining Chinese characters
    import re
    chinese_regex = re.compile(r'[\u4e00-\u9fff]+')
    remaining = chinese_regex.findall(translated)
    unique_remaining = set(remaining)
    
    print(f"\nRemaining Chinese phrases: {len(unique_remaining)}")
    if unique_remaining:
        print("Sample of remaining phrases:")
        for phrase in list(unique_remaining)[:20]:
            print(f"  - {phrase}")

if __name__ == '__main__':
    main()
